import type { AppState } from "@/lib/types";

const today = new Date();
const iso = (offsetDays: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + offsetDays);
  date.setHours(8, 0, 0, 0);
  return date.toISOString();
};

export const defaultGlobalExercises: AppState["exercises"] = [
  {
    id: "ex_back_squat",
    name: "Takakyykky",
    category: "Alavartalo",
    equipment: "Levantotanko",
    cue: "Asetu tukevasti tangon alle, jännitä keskivartalo ja pidä rintakehä avoinna. Istuudu hallitusti alas koko jalkapohjalle ja aja ylös painamalla lattiaa pois alta.",
    scope: "global",
  },
  {
    id: "ex_front_squat",
    name: "Etukyykky",
    category: "Alavartalo",
    equipment: "Levantotanko",
    cue: "Pidä kyynärpäät korkealla ja tanko tukevasti etuharteilla. Laskeudu suoraan alas hallitusti ja nouse ylös säilyttäen pysty vartalo ja keskivartalon tuki.",
    scope: "global",
  },
  {
    id: "ex_goblet_squat",
    name: "Goblet-kyykky",
    category: "Alavartalo",
    equipment: "Käsipaino / Kahvakuula",
    cue: "Pidä paino lähellä rintaa ja rintakehä avoinna koko liikkeen ajan. Laskeudu alas kantapäät maassa ja työnnä polvia varpaiden suuntaan.",
    scope: "global",
  },
  {
    id: "ex_leg_press",
    name: "Jalkaprässi",
    category: "Alavartalo",
    equipment: "Jalkaprässi",
    cue: "Aseta jalat tasaisesti levylle ja pidä alaselkä kiinni tuessa. Laskeudu hallitusti sopivaan syvyyteen ja työnnä levy ylös ilman että polvet lukittuvat voimalla.",
    scope: "global",
  },
  {
    id: "ex_hack_squat",
    name: "Hack-kyykky",
    category: "Alavartalo",
    equipment: "Hack-laite",
    cue: "Pidä selkä tukevasti alustaa vasten ja keskivartalo jännittyneenä. Laskeudu hallitusti alas ja työnnä ylös koko jalkapohjan kautta.",
    scope: "global",
  },
  {
    id: "ex_split_squat",
    name: "Bulgarialainen askelkyykky",
    category: "Alavartalo",
    equipment: "Käsipainot",
    cue: "Aseta etujalka tukevasti maahan ja pidä paino pääosin etujalalla. Laskeudu suoraan alas hallitusti ja työnnä ylös ilman että takajalka tekee liikaa työtä.",
    scope: "global",
  },
  {
    id: "ex_walking_lunge",
    name: "Kävelyaskelkyykky",
    category: "Alavartalo",
    equipment: "Käsipainot",
    cue: "Pidä vartalo pystyssä ja askel riittävän pitkänä, jotta etupolvi pysyy hallinnassa. Työnnä jokainen askel ylös etujalan kautta ja säilytä tasainen rytmi.",
    scope: "global",
  },
  {
    id: "ex_step_up",
    name: "Step-up",
    category: "Alavartalo",
    equipment: "Boksi + käsipainot",
    cue: "Aseta koko etujalka korokkeelle ja pidä lantio suorassa. Työnnä itsesi ylös etujalan kautta ilman ponnistusta takajalalla.",
    scope: "global",
  },
  {
    id: "ex_romanian_deadlift",
    name: "Romanialainen maastaveto",
    category: "Takaketju",
    equipment: "Levantotanko",
    cue: "Pidä tanko lähellä reisiä ja selkä neutraalina koko liikkeen ajan. Vie lantiota taakse hallitusti ja nouse ylös puristamalla pakarat.",
    scope: "global",
  },
  {
    id: "ex_deadlift",
    name: "Maastaveto",
    category: "Takaketju",
    equipment: "Levantotanko",
    cue: "Asetu tangon päälle siten, että tanko on lähellä sääriä ja selkä neutraali. Jännitä keskivartalo, työnnä lattiaa pois jaloilla ja vedä tanko ylös vartaloa pitkin.",
    scope: "global",
  },
  {
    id: "ex_sumo_deadlift",
    name: "Sumomaastaveto",
    category: "Takaketju",
    equipment: "Levantotanko",
    cue: "Aseta jalat leveälle ja polvet varpaiden suuntaan. Pidä rintakehä korkealla, työnnä lattiaa sivuille ja vedä tanko ylös lähellä vartaloa.",
    scope: "global",
  },
  {
    id: "ex_good_morning",
    name: "Good morning",
    category: "Takaketju",
    equipment: "Levantotanko",
    cue: "Pidä polvissa kevyt koukku ja tanko vakaasti yläselällä. Työnnä lantiota taakse ja pidä selkä neutraalina koko alas- ja ylösliikkeen ajan.",
    scope: "global",
  },
  {
    id: "ex_hip_thrust",
    name: "Hip thrust",
    category: "Pakarat",
    equipment: "Penkki + tanko",
    cue: "Aseta yläselkä penkkiä vasten ja pidä leuka kevyesti alhaalla. Työnnä lantio ylös puristaen pakaroita ja vältä alaselän yliojennusta.",
    scope: "global",
  },
  {
    id: "ex_glute_bridge",
    name: "Glute bridge",
    category: "Pakarat",
    equipment: "Kehonpaino / tanko",
    cue: "Pidä jalkapohjat tukevasti maassa ja kylkiluut alhaalla. Nosta lantio linjaan hallitusti ja purista pakarat yläasennossa.",
    scope: "global",
  },
  {
    id: "ex_leg_curl",
    name: "Takareisikoukistus",
    category: "Alavartalo",
    equipment: "Leg curl -laite",
    cue: "Pidä lantio tuettuna alustaa vasten ja liike rauhallisena. Vedä kantapäät kohti pakaroita hallitusti ja laske takaisin ilman heilautusta.",
    scope: "global",
  },
  {
    id: "ex_leg_extension",
    name: "Jalanojennus",
    category: "Alavartalo",
    equipment: "Leg extension -laite",
    cue: "Säädä polvi nivelakselin kohdalle ja pidä reidet tukevasti penkissä. Ojenna polvet hallitusti, pysäytä hetkeksi yläasentoon ja laske rauhassa alas.",
    scope: "global",
  },
  {
    id: "ex_calf_raise_standing",
    name: "Pohjenousu seisten",
    category: "Alavartalo",
    equipment: "Pohjelaite / käsipainot",
    cue: "Anna kantapäiden laskea alas täyteen venytykseen ja pidä paino päkiöillä. Nouse hallitusti ylös varpaille asti ja pysäytä hetkeksi yläasentoon.",
    scope: "global",
  },
  {
    id: "ex_calf_raise_seated",
    name: "Pohjenousu istuen",
    category: "Alavartalo",
    equipment: "Istuva pohjelaite",
    cue: "Pidä reidet tukevasti alustaa vasten ja hae pohkeeseen täysi venytys ala-asennossa. Nouse hallitusti päkiöille ja jarruta lasku takaisin alas.",
    scope: "global",
  },
  {
    id: "ex_hip_abduction_machine",
    name: "Lonkan loitonnus laitteessa",
    category: "Pakarat",
    equipment: "Abductor-laite",
    cue: "Pidä lantio tukevasti alustaa vasten ja keskivartalo vakaana. Avaa jalat ulos hallitusti ja palauta liike takaisin ilman nykäisyä.",
    scope: "global",
  },
  {
    id: "ex_hip_adduction_machine",
    name: "Lonkan lähennys laitteessa",
    category: "Alavartalo",
    equipment: "Adductor-laite",
    cue: "Pidä lantio paikallaan ja aloita liike hallitusti sisäreisillä. Purista jalat yhteen loppuasentoon ja palauta rauhassa alkuun.",
    scope: "global",
  },
  {
    id: "ex_bench_press",
    name: "Penkkipunnerrus",
    category: "Rinta",
    equipment: "Penkki + tanko",
    cue: "Asetu penkille selinmakuulle jalat tukevasti maahan. Vedä lapaluut yhteen ja alas sekä pidä alaselässä kevyt kaari.\n\nOta tangosta hieman hartioita leveämpi ote ja pidä ranteet suorina. Aloita tanko hartioiden yläpuolelta.\n\nLaske tanko hallitusti rinnan alaosaan kyynärpäät noin 30-60 asteen kulmassa vartalosta.\n\nPunnerra tanko takaisin ylös loivassa kaaressa suorille käsille. Pidä keho jännittyneenä ja vältä pomputusta.\n\nHengitä sisään alas laskiessa ja ulos ylös työntäessä.",
    scope: "global",
  },
  {
    id: "ex_incline_bench_press",
    name: "Vinopenkki tangolla",
    category: "Rinta",
    equipment: "Vinopenkki + tanko",
    cue: "Vedä lapaluut yhteen ja pidä jalat tukevasti maassa. Laske tanko hallitusti ylä- tai keskirinnan suuntaan ja punnersa ylös ilman että kyynärpäät leviävät liikaa.",
    scope: "global",
  },
  {
    id: "ex_decline_bench_press",
    name: "Alavinopenkki tangolla",
    category: "Rinta",
    equipment: "Alavinopenkki + tanko",
    cue: "Pidä lapatuet tiukkana ja ranne-tankolinja vakaana. Laske tanko hallitusti alarinnan suuntaan ja työnnä takaisin ylös tasaisella voimalla.",
    scope: "global",
  },
  {
    id: "ex_db_bench_press",
    name: "Käsipainopenkki",
    category: "Rinta",
    equipment: "Penkki + käsipainot",
    cue: "Vedä lapaluut yhteen ja pidä käsipainot hallinnassa koko liikeradan ajan. Laske kyynärpäät hallitusti alas ja työnnä painot ylös loivassa kaaressa.",
    scope: "global",
  },
  {
    id: "ex_incline_db_press",
    name: "Vinopenkki käsipainoilla",
    category: "Rinta",
    equipment: "Vinopenkki + käsipainot",
    cue: "Pidä lapatuet aktiivisina ja olkapäät alhaalla koko sarjan ajan. Laske käsipainot hallitusti alas ja työnnä takaisin ylös vakaalla liikeradalla.",
    scope: "global",
  },
  {
    id: "ex_chest_fly_db",
    name: "Rintafly käsipainoilla",
    category: "Rinta",
    equipment: "Penkki + käsipainot",
    cue: "Pidä kyynärpäissä kevyt koukku ja rintakehä avoinna. Avaa kädet hallitusti venytykseen ja tuo painot takaisin yhteen ilman että hartiat nousevat.",
    scope: "global",
  },
  {
    id: "ex_cable_fly",
    name: "Taljafly",
    category: "Rinta",
    equipment: "Talja",
    cue: "Asetu vakaaseen asentoon ja pidä rintakehä korkealla. Vie kädet yhteen kaarella rintaa puristaen ja palauta hallitusti venytykseen.",
    scope: "global",
  },
  {
    id: "ex_pec_deck",
    name: "Pec deck",
    category: "Rinta",
    equipment: "Pec deck -laite",
    cue: "Pidä hartiat alhaalla ja kyynärpäät pehmeinä. Purista kädet yhteen rinnan avulla ja jarruta palautus takaisin venytykseen.",
    scope: "global",
  },
  {
    id: "ex_push_up",
    name: "Punnerrus",
    category: "Rinta",
    equipment: "Kehonpaino",
    cue: "Pidä vartalo suorassa linjassa päästä kantapäihin ja keskivartalo tiukkana. Laskeudu hallitusti alas ja työnnä ylös ilman että lantio roikkuu.",
    scope: "global",
  },
  {
    id: "ex_dips",
    name: "Dippi",
    category: "Rinta / ojentajat",
    equipment: "Dippiteline",
    cue: "Pidä hartiat alhaalla ja rintakehä avoinna. Laskeudu hallitusti kyynärpäät takaviistoon ja työnnä itsesi ylös ilman heilautusta.",
    scope: "global",
  },
  {
    id: "ex_overhead_press",
    name: "Pystypunnerrus tangolla",
    category: "Hartiat",
    equipment: "Levantotanko",
    cue: "Purista pakarat ja keskivartalo tiukaksi ennen nostoa. Työnnä tanko suoraan ylös pään yli ja vie pää läpi yläasennossa.",
    scope: "global",
  },
  {
    id: "ex_seated_db_press",
    name: "Istuva pystypunnerrus käsipainoilla",
    category: "Hartiat",
    equipment: "Penkki + käsipainot",
    cue: "Asetu tukevasti penkkiin ja pidä kyynärpäät ranteiden alla. Punnerra painot suoraan ylös hallitusti ja laske takaisin ilman että hartiat kohoavat.",
    scope: "global",
  },
  {
    id: "ex_arnold_press",
    name: "Arnold press",
    category: "Hartiat",
    equipment: "Käsipainot",
    cue: "Aloita kämmenet itseä kohti kyynärpäät edessä. Kierrä kädet punnerruksen aikana ylös ja palauta liike hallitusti takaisin alkuasentoon.",
    scope: "global",
  },
  {
    id: "ex_lateral_raise",
    name: "Vipunosto sivulle",
    category: "Hartiat",
    equipment: "Käsipainot / talja",
    cue: "Pidä kyynärpäissä kevyt kulma ja nosta kädet sivuille hartialinjalle asti. Vältä vauhdinottoa ja pidä niska rentona.",
    scope: "global",
  },
  {
    id: "ex_front_raise",
    name: "Vipunosto eteen",
    category: "Hartiat",
    equipment: "Käsipainot / levypaino",
    cue: "Pidä keskivartalo vakaana ja nosta paino hallitusti eteen hartialinjalle. Laske takaisin alas ilman että nojaat taakse.",
    scope: "global",
  },
  {
    id: "ex_rear_delt_fly",
    name: "Takaolkapääfly",
    category: "Hartiat",
    equipment: "Käsipainot / pec deck",
    cue: "Nojaa eteenpäin vakaasti ja pidä niska neutraalina. Avaa kädet sivuille takaolkapäillä ja jarruta palautus alas.",
    scope: "global",
  },
  {
    id: "ex_upright_row",
    name: "Pystysoutu",
    category: "Hartiat",
    equipment: "Tanko / käsipainot",
    cue: "Vedä paino ylös vartalon läheltä kyynärpäät johtavana. Pidä liike hallittuna ja lopeta ennen kuin hartiat nousevat korviin.",
    scope: "global",
  },
  {
    id: "ex_row",
    name: "Kulmasoutu",
    category: "Selkä",
    equipment: "Käsipainot",
    cue: "Pidä tuki vakaana ja selkä neutraalina. Vedä kyynärpää kohti lantiota ja purista lapaa yhteen yläasennossa.",
    scope: "global",
  },
  {
    id: "ex_barbell_row",
    name: "Kulmasoutu tangolla",
    category: "Selkä",
    equipment: "Levantotanko",
    cue: "Hae vahva etunoja ja pidä keskivartalo tiukkana. Vedä tanko alavatsalle ilman että ylävartalo nousee.",
    scope: "global",
  },
  {
    id: "ex_chest_supported_row",
    name: "Rintasoutu penkiltä",
    category: "Selkä",
    equipment: "Vinopenkki + käsipainot",
    cue: "Pidä rintakehä tukevasti penkkiä vasten koko sarjan ajan. Vedä kyynärpäät taakse ja purista lapoja yhteen yläasennossa.",
    scope: "global",
  },
  {
    id: "ex_seated_cable_row",
    name: "Istuva soutu taljassa",
    category: "Selkä",
    equipment: "Talja",
    cue: "Istahda vakaasti ja pidä rintakehä korkealla. Vedä kahva kohti napaa, pysäytä hetkeksi ja palauta rauhallisesti.",
    scope: "global",
  },
  {
    id: "ex_low_cable_row",
    name: "Alatalja",
    category: "Selkä",
    equipment: "Alatalja",
    cue: "Pidä rintakehä ylhäällä ja keskivartalo vakaana koko vedon ajan. Vedä kyynärpäät taakse ja jarruta palautus hallitusti alkuun.",
    scope: "global",
  },
  {
    id: "ex_lat_pulldown",
    name: "Ylätalja",
    category: "Selkä",
    equipment: "Ylätalja",
    cue: "Pidä rintakehä ylhäällä ja aloita veto lapojen aktivoinnilla. Vedä tanko ylärinnan suuntaan kyynärpäät alas ja taakse ilman nykäisyä.",
    scope: "global",
  },
  {
    id: "ex_pulldown",
    name: "Pulldown",
    category: "Selkä",
    equipment: "Ylätalja",
    cue: "Ota tangosta hartioita leveämpi ote ja pidä rintakehä ylhäällä. Vedä tanko ylärinnan suuntaan latseilla, kyynärpäät alas ja taakse, ja jarruta palautus hallitusti yläasentoon.",
    scope: "global",
  },
  {
    id: "ex_pull_up",
    name: "Leuanveto myötäotteella",
    category: "Selkä",
    equipment: "Leuanvetotanko",
    cue: "Aloita roikunnasta aktivoimalla lavat ja jännittämällä keskivartalo. Vedä itsesi ylös rinta kohti tankoa ilman heiluriliikettä.",
    scope: "global",
  },
  {
    id: "ex_chin_up",
    name: "Leuanveto vastaotteella",
    category: "Selkä / hauis",
    equipment: "Leuanvetotanko",
    cue: "Pidä keskivartalo tiukkana ja aloita veto lapojen kautta. Vedä leuka tangon yli hallitusti ja laskeudu täyteen roikuntaan kontrolloidusti.",
    scope: "global",
  },
  {
    id: "ex_single_arm_cable_row",
    name: "Yhden käden soutu taljassa",
    category: "Selkä",
    equipment: "Talja",
    cue: "Pidä lantio ja rintakehä vakaana koko vedon ajan. Vedä kyynärpää taakse kyljen suuntaan ja jarruta palautus.",
    scope: "global",
  },
  {
    id: "ex_face_pull",
    name: "Face pull",
    category: "Yläselkä",
    equipment: "Talja + köysi",
    cue: "Vedä köysi kasvojen korkeudelle kyynärpäät leveinä. Kierrä peukalot taakse ja pidä yläselkä aktiivisena.",
    scope: "global",
  },
  {
    id: "ex_shrug",
    name: "Hartiannosto",
    category: "Yläselkä",
    equipment: "Käsipainot / tanko",
    cue: "Pidä kädet suorina ja nosta hartiat suoraan ylöspäin. Pysäytä hetkeksi yläasennossa ja laske hitaasti alas.",
    scope: "global",
  },
  {
    id: "ex_straight_arm_pulldown",
    name: "Suorin käsin ylätaljaveto",
    category: "Selkä",
    equipment: "Talja",
    cue: "Pidä rintakehä avoinna ja kyynärpäissä kevyt kulma. Vedä kädet alas lantiolle latseilla ilman että nojaat liikaa.",
    scope: "global",
  },
  {
    id: "ex_close_grip_bench_press",
    name: "Kapea penkkipunnerrus",
    category: "Ojentajat",
    equipment: "Penkki + tanko",
    cue: "Pidä ote hartioita kapeampana ja kyynärpäät lähellä vartaloa. Laske tanko hallitusti alarinnan suuntaan ja punnersa ylös ojentajilla.",
    scope: "global",
  },
  {
    id: "ex_tricep_pushdown",
    name: "Ojentajapunnerrus taljassa",
    category: "Ojentajat",
    equipment: "Talja",
    cue: "Pidä kyynärpäät kiinni kyljissä ja hartiat alhaalla. Ojenna kyynärpäät loppuun asti ja palauta hallitusti takaisin ylös.",
    scope: "global",
  },
  {
    id: "ex_overhead_tricep_extension",
    name: "Ojentaja pään yli",
    category: "Ojentajat",
    equipment: "Köysitalja / käsipaino",
    cue: "Pidä yläkädet paikallaan ja kyynärpäät osoittamassa eteen. Laske paino venytykseen pään taakse ja ojenna hallitusti ylös.",
    scope: "global",
  },
  {
    id: "ex_skullcrusher",
    name: "Ranskalainen punnerrus",
    category: "Ojentajat",
    equipment: "EZ-tanko / käsipainot",
    cue: "Pidä olkavarret mahdollisimman paikallaan ja kyynärpäät osoittamassa ylös. Laske paino hallitusti otsan taakse ja ojenna takaisin ylös.",
    scope: "global",
  },
  {
    id: "ex_barbell_curl",
    name: "Hauiskääntö tangolla",
    category: "Hauis",
    equipment: "EZ-tanko / suora tanko",
    cue: "Pidä kyynärpäät kyljissä ja rintakehä avoinna. Nosta tanko ylös ilman heilautusta ja laske hallitusti alas.",
    scope: "global",
  },
  {
    id: "ex_db_curl",
    name: "Hauiskääntö käsipainoilla",
    category: "Hauis",
    equipment: "Käsipainot",
    cue: "Pidä kyynärpäät paikallaan ja kierrä kämmenet ylös noston aikana. Laske painot hitaasti takaisin alas täyteen venytykseen.",
    scope: "global",
  },
  {
    id: "ex_hammer_curl",
    name: "Vasarahauiskääntö",
    category: "Hauis",
    equipment: "Käsipainot",
    cue: "Pidä ranteet neutraalina ja kyynärpäät lähellä vartaloa. Nosta painot hallitusti ylös ja laske alas ilman heilautusta.",
    scope: "global",
  },
  {
    id: "ex_preacher_curl",
    name: "Scott-hauiskääntö",
    category: "Hauis",
    equipment: "Scott-penkki",
    cue: "Pidä olkavarret tukevasti padilla ja hartiat rentoina. Tee täysi liikerata hallitusti ja vältä painon pudottamista alas.",
    scope: "global",
  },
  {
    id: "ex_cable_curl",
    name: "Hauiskääntö taljassa",
    category: "Hauis",
    equipment: "Talja",
    cue: "Pidä jännitys hauiksessa koko liikkeen ajan ja kyynärpäät paikoillaan. Purista yläasennossa ja palauta hitaasti.",
    scope: "global",
  },
  {
    id: "ex_plank",
    name: "Lankku",
    category: "Core",
    equipment: "Kehonpaino",
    cue: "Purista pakarat ja keskivartalo tiukaksi koko pidon ajan. Pidä vartalo suorassa linjassa ilman että alaselkä notkahtaa.",
    scope: "global",
  },
  {
    id: "ex_side_plank",
    name: "Sivulankku",
    category: "Core",
    equipment: "Kehonpaino",
    cue: "Pidä kyynärpää suoraan olkapään alla ja lantio korkealla. Säilytä vartalo suorassa linjassa koko pidon ajan.",
    scope: "global",
  },
  {
    id: "ex_dead_bug",
    name: "Dead bug",
    category: "Core",
    equipment: "Kehonpaino",
    cue: "Pidä alaselkä kevyesti lattiaa vasten ja kyljet aktiivisina. Ojenna raajat vuorotellen hallitusti ilman että selkä irtoaa alustasta.",
    scope: "global",
  },
  {
    id: "ex_ab_wheel",
    name: "Ab wheel roll-out",
    category: "Core",
    equipment: "Ab wheel",
    cue: "Jännitä keskivartalo ennen rullausta ja pidä lantio hallinnassa. Vie rulla eteen niin pitkälle kuin pystyt ilman että alaselkä notkahtaa.",
    scope: "global",
  },
  {
    id: "ex_hanging_leg_raise",
    name: "Jalkojen nosto roikkuen",
    category: "Core",
    equipment: "Leuanvetotanko",
    cue: "Aloita vakaasta roikunnasta ja pidä lapatuet aktiivisina. Nosta jalat hallitusti ylös ilman heilautusta ja laske rauhassa alas.",
    scope: "global",
  },
  {
    id: "ex_cable_crunch",
    name: "Vatsarutistus taljassa",
    category: "Core",
    equipment: "Talja",
    cue: "Pidä lantio paikallaan ja pyöristä yläselkää vatsan avulla. Rutista hallitusti alas ja palaa ylös ilman että vedät käsillä liikaa.",
    scope: "global",
  },
  {
    id: "ex_russian_twist",
    name: "Russian twist",
    category: "Core",
    equipment: "Levy / käsipaino",
    cue: "Pidä rintakehä ryhdikkäänä ja keskivartalo aktiivisena. Kierrä rintarangasta puolelta toiselle hallitusti ilman pelkkää käsien heilautusta.",
    scope: "global",
  },
  {
    id: "ex_pallof_press",
    name: "Pallof press",
    category: "Core",
    equipment: "Talja / kuminauha",
    cue: "Asetu vakaaseen asentoon ja jännitä keskivartalo. Punnerra kahva eteen ja vastusta taljan vetoa ilman että lantio kiertyy.",
    scope: "global",
  },
  {
    id: "ex_farmers_walk",
    name: "Farmer's walk",
    category: "Koko kroppa",
    equipment: "Käsipainot / farmer-kahvat",
    cue: "Seiso ryhdikkäästi hartiat alhaalla ja pidä ote vahvana. Kävele lyhyin hallituin askelin ilman että kuorma heiluttaa vartaloa.",
    scope: "global",
  },
  {
    id: "ex_sled_push",
    name: "Kelkan työntö",
    category: "Koko kroppa",
    equipment: "Kelkka",
    cue: "Kallista vartalo kevyesti eteen ja pidä keskivartalo tiukkana. Työnnä kelkkaa tasaisella rytmillä koko jalkapohjan kautta.",
    scope: "global",
  },
  {
    id: "ex_kettlebell_swing",
    name: "Kahvakuulaheilautus",
    category: "Takaketju",
    equipment: "Kahvakuula",
    cue: "Vie lantio taakse ja pidä selkä neutraalina ennen heilautusta. Räjäytä lantio eteen ja anna käsien vain ohjata kuulaa.",
    scope: "global",
  },
  {
    id: "ex_thruster",
    name: "Thruster",
    category: "Koko kroppa",
    equipment: "Levantotanko / käsipainot",
    cue: "Pidä keskivartalo tiukkana ja laskeudu hallittuun etukyykkyyn. Nouse voimakkaasti ylös ja jatka liike suoraan pystypunnerrukseksi.",
    scope: "global",
  },
  // --- Laajennettu liikepankki: alavartalo ---
  {
    id: "ex_smith_squat",
    name: "Kyykky smith-laitteessa",
    category: "Alavartalo",
    equipment: "Smith-laite",
    cue: "Aseta tanko yläselälle Smith-laitteen kelkkaan ja jalat hieman eteen. Laskeudu hallitusti alas keskivartalo tiukkana ja punnerra suoraa rataa ylös.",
    scope: "global",
  },
  {
    id: "ex_box_squat",
    name: "Boksikyykky",
    category: "Alavartalo",
    equipment: "Levantotanko + boksi",
    cue: "Kyykisty hallitusti boksille viemällä lantio taakse, pidä jännitys hetki ja nouse räjähtävästi ylös pyöristämättä selkää.",
    scope: "global",
  },
  {
    id: "ex_belt_squat",
    name: "Vyökyykky",
    category: "Alavartalo",
    equipment: "Vyökyykkylaite",
    cue: "Kiinnitä paino lantiovyöhön ja seiso korokkeilla. Laskeudu syvään kyykkyyn selkä rentona ja punnerra kantapäiden kautta ylös.",
    scope: "global",
  },
  {
    id: "ex_sissy_squat",
    name: "Sissy-kyykky",
    category: "Alavartalo",
    equipment: "Kehonpaino / sissy-laite",
    cue: "Nojaa ylävartaloa taakse ja nouse päkiöille samalla kun viet polvet eteen ja alas. Pidä lantio ja vartalo suorana linjana koko liikkeen ajan.",
    scope: "global",
  },
  {
    id: "ex_pistol_squat",
    name: "Pistoolikyykky",
    category: "Alavartalo",
    equipment: "Kehonpaino",
    cue: "Ojenna toinen jalka eteen ja laskeudu yhden jalan kyykkyyn hallitusti. Pidä kantapää maassa ja keskivartalo tiukkana, nouse tasaisesti ylös.",
    scope: "global",
  },
  {
    id: "ex_reverse_lunge",
    name: "Taakse-askelkyykky",
    category: "Alavartalo",
    equipment: "Käsipainot",
    cue: "Astu hallitusti taakse ja laskeudu, kunnes molemmat polvet ovat noin 90 asteessa. Paina etujalan kantapäästä takaisin pystyyn.",
    scope: "global",
  },
  {
    id: "ex_single_leg_press",
    name: "Yhden jalan jalkaprässi",
    category: "Alavartalo",
    equipment: "Jalkaprässi",
    cue: "Aseta yksi jalka levyn keskelle ja laskeudu hallitusti polvi kohti rintaa. Punnerra kantapään kautta lähes suoraksi lukitsematta polvea.",
    scope: "global",
  },
  {
    id: "ex_seated_leg_curl",
    name: "Istuva takareisikoukistus",
    category: "Alavartalo",
    equipment: "Istuva leg curl -laite",
    cue: "Säädä tukityyny reisien päälle ja koukista kantapäät hallitusti taakse penkin alle. Purista takareisiä ala-asennossa ja palauta jarruttaen.",
    scope: "global",
  },
  {
    id: "ex_calf_press",
    name: "Pohkeet prässissä",
    category: "Alavartalo",
    equipment: "Jalkaprässi",
    cue: "Aseta päkiät levyn alareunaan ja anna kantapäiden laskeutua venytykseen. Työnnä päkiöillä paino ylös täyteen ojennukseen ja jarruta alas.",
    scope: "global",
  },
  // --- Takaketju & pakarat ---
  {
    id: "ex_trap_bar_deadlift",
    name: "Trap bar -maastaveto",
    category: "Takaketju",
    equipment: "Trap bar",
    cue: "Astu kuusikulmatangon sisään ja ota kahvoista kiinni selkä neutraalina. Aja lattiaa pois alta ja nouse pystyyn lantio ja polvet yhtä aikaa ojentaen.",
    scope: "global",
  },
  {
    id: "ex_rack_pull",
    name: "Rack pull",
    category: "Takaketju",
    equipment: "Levantotanko + teline",
    cue: "Aseta tanko telineeseen polvien korkeudelle. Vedä lapaluut taakse ja nouse pystyyn lukiten lantio, pidä selkä koko ajan neutraalina.",
    scope: "global",
  },
  {
    id: "ex_single_leg_rdl",
    name: "Yhden jalan romanialainen maastaveto",
    category: "Takaketju",
    equipment: "Käsipaino",
    cue: "Saranoi lantiosta eteen ja ojenna takajalka taakse pitäen selkä suorana. Tunne venytys takareidessä ja palaudu pystyyn pakaraa jännittäen.",
    scope: "global",
  },
  {
    id: "ex_nordic_curl",
    name: "Nordic hamstring curl",
    category: "Takaketju",
    equipment: "Kehonpaino",
    cue: "Lukitse nilkat tuen alle ja laskeudu hitaasti eteenpäin jarruttaen takareisillä. Pidä lantio suorassa ja työnnä käsillä takaisin ylös tarvittaessa.",
    scope: "global",
  },
  {
    id: "ex_back_extension",
    name: "Selän ojennus",
    category: "Takaketju",
    equipment: "Selkäpenkki",
    cue: "Saranoi lantiosta alas selkä neutraalina ja nouse ylös pakaroita ja alaselkää jännittäen. Älä yliojennna yläasennossa.",
    scope: "global",
  },
  {
    id: "ex_cable_pull_through",
    name: "Taljaveto jalkojen välistä",
    category: "Pakarat",
    equipment: "Talja + köysi",
    cue: "Seiso selkä taljaa kohti ja vie köysi jalkojen välistä. Saranoi lantiosta taakse ja työnnä lantio eteen pakaroita puristaen.",
    scope: "global",
  },
  {
    id: "ex_cable_kickback",
    name: "Pakarapotku taljassa",
    category: "Pakarat",
    equipment: "Talja + nilkkalenkki",
    cue: "Kiinnitä nilkkalenkki ja potkaise jalka hallitusti taakse pakaraa jännittäen. Palauta jarruttaen heiluttamatta ylävartaloa.",
    scope: "global",
  },
  // --- Rinta ---
  {
    id: "ex_machine_chest_press",
    name: "Penkkipunnerrus laitteessa",
    category: "Rinta",
    equipment: "Punnerruslaite",
    cue: "Säädä istuin niin että kahvat ovat keskirinnan korkeudella. Punnerra hallitusti eteen lähes suoraksi ja palauta jarruttaen rinnan venytykseen.",
    scope: "global",
  },
  {
    id: "ex_smith_incline_press",
    name: "Vinopenkki smith-laitteessa",
    category: "Rinta",
    equipment: "Smith-laite",
    cue: "Aseta vinopenkki Smith-tangon alle ylärinnan kohdalle. Laske tanko hallitusti ylärintaan ja punnerra suoraa rataa ylös.",
    scope: "global",
  },
  {
    id: "ex_cable_crossover",
    name: "Taljaveto ristiin",
    category: "Rinta",
    equipment: "Talja",
    cue: "Säädä taljat ylös ja astu askel eteen kahvat käsissä. Tuo kahvat kaarella alas ja ristiin rintalihasta puristaen, palauta hallitusti.",
    scope: "global",
  },
  {
    id: "ex_incline_cable_fly",
    name: "Vinofly taljassa",
    category: "Rinta",
    equipment: "Talja",
    cue: "Säädä taljat alas ja astu eteen kahvat käsissä. Tuo kahvat kaarella ylös ja yhteen ylärintaa puristaen, jarruta takaisin venytykseen.",
    scope: "global",
  },
  {
    id: "ex_db_pullover",
    name: "Pullover käsipainolla",
    category: "Rinta",
    equipment: "Penkki + käsipaino",
    cue: "Makaa penkillä ja pidä käsipainoa lähes suorilla käsillä rinnan päällä. Laske paino kaarella pään taakse venytykseen ja vedä takaisin rintalihaksilla.",
    scope: "global",
  },
  {
    id: "ex_decline_push_up",
    name: "Jalat koholla -punnerrus",
    category: "Rinta",
    equipment: "Kehonpaino",
    cue: "Aseta jalat korokkeelle ja kädet hartioita leveämmälle. Laskeudu hallitusti rinta kohti lattiaa ja punnerra ylös keho suorana lankkuna.",
    scope: "global",
  },
  {
    id: "ex_svend_press",
    name: "Svend press",
    category: "Rinta",
    equipment: "Levypaino",
    cue: "Purista kahta levyä yhteen kämmenten välissä rinnan edessä. Työnnä kädet suoraksi eteen rintalihasta puristaen ja vedä hallitusti takaisin.",
    scope: "global",
  },
  // --- Hartiat ---
  {
    id: "ex_machine_shoulder_press",
    name: "Pystypunnerrus laite",
    category: "Hartiat",
    equipment: "Punnerruslaite",
    cue: "Säädä istuin niin että kahvat ovat hartioiden tasolla. Punnerra hallitusti ylös lähes suoraksi ja laske jarruttaen lukitsematta kyynärpäitä.",
    scope: "global",
  },
  {
    id: "ex_cable_lateral_raise",
    name: "Vipunosto sivulle taljassa",
    category: "Hartiat",
    equipment: "Talja",
    cue: "Seiso kylki taljaa kohti ja nosta käsi sivukautta hartialinjaan asti. Johda liikettä kyynärpäästä ja jarruta hallitusti alas.",
    scope: "global",
  },
  {
    id: "ex_machine_lateral_raise",
    name: "Vipunosto laitteessa",
    category: "Hartiat",
    equipment: "Sivunostolaite",
    cue: "Asetu laitteeseen kyynärpäät tukityynyjä vasten. Nosta kyynärpäät sivukautta hartialinjaan ja laske jarruttaen.",
    scope: "global",
  },
  {
    id: "ex_reverse_pec_deck",
    name: "Käänteinen pec deck",
    category: "Hartiat",
    equipment: "Pec deck -laite",
    cue: "Istu kasvot laitetta kohti ja ota kahvoista kiinni edessä. Avaa kädet kaarella taakse takaolkapäitä ja lapoja puristaen, palauta hallitusti.",
    scope: "global",
  },
  {
    id: "ex_landmine_press",
    name: "Landmine-punnerrus",
    category: "Hartiat",
    equipment: "Landmine / tanko",
    cue: "Pidä tangon päätä toisella kädellä olkapään edessä. Punnerra tanko ylös vinosti eteen ja laske hallitusti keskivartalo tiukkana.",
    scope: "global",
  },
  {
    id: "ex_cable_front_raise",
    name: "Vipunosto eteen taljassa",
    category: "Hartiat",
    equipment: "Talja",
    cue: "Seiso selkä taljaa kohti ja nosta kahva lähes suorin käsin eteen hartialinjaan. Jarruta hallitusti alas heiluttamatta vartaloa.",
    scope: "global",
  },
  // --- Selkä ---
  {
    id: "ex_t_bar_row",
    name: "T-tankosoutu",
    category: "Selkä",
    equipment: "T-tankolaite",
    cue: "Seiso tangon päällä ja saranoi lantiosta eteen selkä neutraalina. Vedä kahvat kohti vatsaa lapoja yhteen puristaen ja laske hallitusti.",
    scope: "global",
  },
  {
    id: "ex_pendlay_row",
    name: "Pendlay-soutu",
    category: "Selkä",
    equipment: "Levantotanko",
    cue: "Saranoi ylävartalo lattian suuntaiseksi ja anna tangon levätä lattiassa joka toiston välissä. Vedä tanko räjähtävästi vatsaan selkä jännittyneenä.",
    scope: "global",
  },
  {
    id: "ex_machine_row",
    name: "Soutu laitteessa",
    category: "Selkä",
    equipment: "Soutulaite",
    cue: "Asetu rinta tukea vasten ja ota kahvoista kiinni. Vedä kahvat kohti vartaloa lavat yhteen ja palauta jarruttaen hartiat alhaalla.",
    scope: "global",
  },
  {
    id: "ex_wide_grip_pulldown",
    name: "Leveä ylätaljaveto",
    category: "Selkä",
    equipment: "Ylätalja",
    cue: "Ota tangosta leveä ote ja vedä lapoja alas ennen vetoa. Vedä tanko ylärintaan kyynärpäät alas ja taakse, palauta hallitusti.",
    scope: "global",
  },
  {
    id: "ex_close_grip_pulldown",
    name: "Kapea ylätaljaveto",
    category: "Selkä",
    equipment: "Ylätalja",
    cue: "Ota neutraali kapea ote ja vedä lapoja alas. Vedä kahva ylävatsaan kyynärpäät vartalon vierestä ja palauta venytykseen.",
    scope: "global",
  },
  {
    id: "ex_inverted_row",
    name: "Vaakasoutu",
    category: "Selkä",
    equipment: "Smith / tanko",
    cue: "Asetu tangon alle keho suorana ja ota hartioita leveämpi ote. Vedä rinta kohti tankoa lapoja puristaen ja laske hallitusti.",
    scope: "global",
  },
  // --- Ojentajat ---
  {
    id: "ex_rope_pushdown",
    name: "Ojentajapunnerrus köydellä",
    category: "Ojentajat",
    equipment: "Talja + köysi",
    cue: "Pidä kyynärpäät kiinni kyljissä ja työnnä köysi alas levittäen päät liikkeen lopussa. Palauta hallitusti pitäen olkavarret paikallaan.",
    scope: "global",
  },
  {
    id: "ex_overhead_cable_extension",
    name: "Ojentaja pään yli taljassa",
    category: "Ojentajat",
    equipment: "Talja + köysi",
    cue: "Käänny selkä taljaa kohti ja pidä köysi niskan takana kyynärpäät ylhäällä. Ojenna kädet suoraksi eteen ja jarruta venytykseen.",
    scope: "global",
  },
  {
    id: "ex_bench_dip",
    name: "Penkkidippi",
    category: "Ojentajat",
    equipment: "Penkki",
    cue: "Tue kädet penkin reunaan ja laskeudu koukistamalla kyynärpäitä suoraan taakse. Punnerra ylös ojentajilla pitäen vartalo lähellä penkkiä.",
    scope: "global",
  },
  {
    id: "ex_diamond_push_up",
    name: "Timanttipunnerrus",
    category: "Ojentajat",
    equipment: "Kehonpaino",
    cue: "Aseta kädet rinnan alle peukalot ja etusormet vastakkain. Laskeudu hallitusti ja punnerra ylös kyynärpäät lähellä kylkiä.",
    scope: "global",
  },
  {
    id: "ex_db_kickback",
    name: "Ojentajapotku käsipainolla",
    category: "Ojentajat",
    equipment: "Käsipaino",
    cue: "Saranoi ylävartalo eteen ja pidä olkavarsi kyljen vieressä. Ojenna kyynärnivel suoraksi taakse ja jarruta hallitusti.",
    scope: "global",
  },
  // --- Hauis & kyynärvarret ---
  {
    id: "ex_incline_db_curl",
    name: "Hauiskääntö vinopenkissä",
    category: "Hauis",
    equipment: "Vinopenkki + käsipainot",
    cue: "Istu taaksenojatussa vinopenkissä kädet riippuen. Käännä painot ylös olkavarret paikallaan ja jarruta täyteen venytykseen.",
    scope: "global",
  },
  {
    id: "ex_concentration_curl",
    name: "Keskittynyt hauiskääntö",
    category: "Hauis",
    equipment: "Käsipaino",
    cue: "Tue kyynärpää reiden sisäpintaa vasten istuen. Käännä paino ylös hitaasti hauista puristaen ja laske hallitusti.",
    scope: "global",
  },
  {
    id: "ex_spider_curl",
    name: "Spider-hauiskääntö",
    category: "Hauis",
    equipment: "Vinopenkki + käsipainot",
    cue: "Asetu rinta vinopenkin selkänojaa vasten kädet riippuen. Käännä painot ylös olkavarret pystyssä ja jarruta alas.",
    scope: "global",
  },
  {
    id: "ex_reverse_curl",
    name: "Käänteinen hauiskääntö",
    category: "Hauis",
    equipment: "EZ-tanko / käsipainot",
    cue: "Ota yläote tangosta ja pidä kyynärpäät kyljissä. Käännä tanko ylös kyynärvarsia ja hauista jännittäen, laske hallitusti.",
    scope: "global",
  },
  {
    id: "ex_machine_curl",
    name: "Hauiskääntö laitteessa",
    category: "Hauis",
    equipment: "Hauislaite",
    cue: "Aseta olkavarret tukityynylle ja ota kahvoista kiinni. Käännä kahvat ylös hauista puristaen ja palauta jarruttaen täyteen venytykseen.",
    scope: "global",
  },
  {
    id: "ex_wrist_curl",
    name: "Ranteenkoukistus",
    category: "Hauis",
    equipment: "Käsipainot / tanko",
    cue: "Tue kyynärvarret reisille kämmenet ylöspäin. Koukista ranteita ylös kyynärvarren lihaksia jännittäen ja laske hallitusti.",
    scope: "global",
  },
  // --- Core ---
  {
    id: "ex_ab_crunch_machine",
    name: "Vatsarutistus laitteessa",
    category: "Core",
    equipment: "Vatsalaite",
    cue: "Ota kahvoista kiinni ja rutista ylävartalo kasaan vatsalihaksilla. Pyöristä selkää hallitusti ja palauta jarruttaen jännitys säilyttäen.",
    scope: "global",
  },
  {
    id: "ex_hanging_knee_raise",
    name: "Polvennosto roikkuen",
    category: "Core",
    equipment: "Leuanvetotanko",
    cue: "Roiku tangosta rennoin hartioin ja nosta polvet kohti rintaa alavatsaa jännittäen. Laske jalat hitaasti heilumatta.",
    scope: "global",
  },
  {
    id: "ex_decline_sit_up",
    name: "Vatsarutistus alavinopenkillä",
    category: "Core",
    equipment: "Alavinopenkki",
    cue: "Lukitse jalat penkin tukien alle ja laskeudu hallitusti taakse. Nouse ylös vatsalihaksilla pyöristäen selkää, vältä nykimistä.",
    scope: "global",
  },
  {
    id: "ex_bicycle_crunch",
    name: "Polkupyörävatsarutistus",
    category: "Core",
    equipment: "Kehonpaino",
    cue: "Tuo vastakkainen kyynärpää ja polvi yhteen vuorotellen samalla kun ojennat toista jalkaa. Pidä alaselkä kiinni lattiassa ja liike hallittuna.",
    scope: "global",
  },
  {
    id: "ex_mountain_climber",
    name: "Vuorikiipeilijä",
    category: "Core",
    equipment: "Kehonpaino",
    cue: "Ole punnerrusasennossa keho suorana ja vedä polvet vuorotellen kohti rintaa. Pidä lantio matalana ja rytmi tasaisena.",
    scope: "global",
  },
  {
    id: "ex_lying_leg_raise",
    name: "Jalkojen nosto lattialla",
    category: "Core",
    equipment: "Kehonpaino",
    cue: "Makaa selällään kädet vartalon vierellä ja nosta suorat jalat ylös. Laske jalat hitaasti alas pitäen alaselkä kiinni lattiassa.",
    scope: "global",
  },
  {
    id: "ex_cable_woodchop",
    name: "Halonhakkuu taljassa",
    category: "Core",
    equipment: "Talja",
    cue: "Vedä kahva vinosti ylhäältä alas vastakkaisen lonkan ohi keskivartaloa kiertäen. Pidä kädet suorina ja liike hallittuna, toista molemmille puolille.",
    scope: "global",
  },
  {
    id: "ex_bird_dog",
    name: "Lintukoira",
    category: "Core",
    equipment: "Kehonpaino",
    cue: "Ojenna vastakkainen käsi ja jalka suoraan konttausasennosta selkä neutraalina. Pidä lantio vakaana ja palauta hallitusti, vuorottele puolia.",
    scope: "global",
  },
  // --- Koko kroppa & teho ---
  {
    id: "ex_power_clean",
    name: "Power clean",
    category: "Koko kroppa",
    equipment: "Levantotanko",
    cue: "Vedä tanko räjähtävästi lattialta ja ojenna lantio voimakkaasti. Pyöräytä kyynärpäät nopeasti tangon alle ja ota se etutelineeseen puolikyykkyyn.",
    scope: "global",
  },
  {
    id: "ex_push_press",
    name: "Push press",
    category: "Koko kroppa",
    equipment: "Levantotanko",
    cue: "Tee lyhyt jousto polvista ja räjäytä tanko ylös jalkojen avulla. Lukitse kädet suoriksi pään yläpuolelle ja laske hallitusti harteille.",
    scope: "global",
  },
  {
    id: "ex_box_jump",
    name: "Loikka boksille",
    category: "Koko kroppa",
    equipment: "Boksi",
    cue: "Lataa lyhyt jousto ja ponnista molemmilla jaloilla boksille. Laskeudu pehmeästi koko jalkapohjalle polvet jousten ja astu alas.",
    scope: "global",
  },
  {
    id: "ex_burpee",
    name: "Burpee",
    category: "Koko kroppa",
    equipment: "Kehonpaino",
    cue: "Laskeudu kyykkyyn, hyppää jalat taakse punnerrusasentoon ja takaisin. Ponnista lopuksi suorana ylös hypäten, pidä rytmi hallittuna.",
    scope: "global",
  },
  {
    id: "ex_med_ball_slam",
    name: "Kuntopallon isku",
    category: "Koko kroppa",
    equipment: "Kuntopallo",
    cue: "Nosta pallo voimakkaasti pään yläpuolelle ja iske se räjähtävästi lattiaan koko vartalolla. Ota pallo kiinni ja toista rytmikkäästi.",
    scope: "global",
  },
  {
    id: "ex_battle_ropes",
    name: "Battle ropes",
    category: "Koko kroppa",
    equipment: "Taisteluköydet",
    cue: "Pidä köysien päistä kiinni polvet kevyesti koukussa. Tee nopeita aaltoja vuorotahtiin käsillä keskivartalo tiukkana.",
    scope: "global",
  },
  // --- Globaaleiksi nostetut laitevariaatiot (omat nimet säilytetty) ---
  {
    id: "ex_high_row",
    name: "High row",
    category: "Selkä",
    equipment: "Soutulaite",
    cue: "Asetu rinta tukea vasten ja ota kahvoista kiinni yläviistosta. Vedä kahvat kohti ylävartaloa kyynärpäät alaviistoon ja purista lapoja yhteen, palauta hallitusti.",
    scope: "global",
  },
  {
    id: "ex_oblique_raise_bench",
    name: "Kylkinosto selkäpenkissä",
    category: "Core",
    equipment: "Selkäpenkki",
    cue: "Asetu kyljelleen selkäpenkkiin nilkat tuettuna. Nosta ylävartalo sivulle kylkilihaksia jännittäen ja laske hallitusti alas, toista molemmin puolin.",
    scope: "global",
  },
];

export const demoState: AppState = {
  users: [
    {
      id: "user_admin_1",
      role: "admin",
      fullName: "Aino Admin",
      email: "admin@rooki.fit",
      status: "active",
      demoPassword: "demo123",
      createdAt: iso(-30),
      updatedAt: iso(-2),
    },
    {
      id: "user_coach_1",
      role: "coach",
      fullName: "Mika Valmentaja",
      email: "coach@rooki.fit",
      status: "active",
      demoPassword: "demo123",
      age: 34,
      sex: "male",
      createdAt: iso(-25),
      updatedAt: iso(-1),
    },
    {
      id: "user_athlete_1",
      role: "athlete",
      fullName: "Sara Treenaaja",
      email: "sara@rooki.fit",
      status: "active",
      demoPassword: "demo123",
      age: 29,
      sex: "female",
      heightCm: 168,
      weightKg: 67.8,
      waistCm: 74,
      createdAt: iso(-20),
      updatedAt: iso(-1),
    },
    {
      id: "user_athlete_2",
      role: "athlete",
      fullName: "Elias Kehittyjä",
      email: "elias@rooki.fit",
      status: "active",
      demoPassword: "demo123",
      age: 31,
      sex: "male",
      heightCm: 182,
      weightKg: 84.6,
      waistCm: 88,
      createdAt: iso(-18),
      updatedAt: iso(-1),
    },
    {
      id: "user_athlete_3",
      role: "athlete",
      fullName: "Noora Kutsu",
      email: "noora@rooki.fit",
      status: "invited",
      createdAt: iso(-1),
      updatedAt: iso(-1),
    },
  ],
  bodyMeasurements: [
    { id: "measurement_1", userId: "user_athlete_1", heightCm: 168, weightKg: 69.4, waistCm: 76, measuredAt: iso(-42), createdAt: iso(-42) },
    { id: "measurement_2", userId: "user_athlete_1", heightCm: 168, weightKg: 68.9, waistCm: 75.5, measuredAt: iso(-35), createdAt: iso(-35) },
    { id: "measurement_3", userId: "user_athlete_1", heightCm: 168, weightKg: 68.5, waistCm: 75, measuredAt: iso(-28), createdAt: iso(-28) },
    { id: "measurement_4", userId: "user_athlete_1", heightCm: 168, weightKg: 68.2, waistCm: 74.5, measuredAt: iso(-21), createdAt: iso(-21) },
    { id: "measurement_5", userId: "user_athlete_1", heightCm: 168, weightKg: 68, waistCm: 74, measuredAt: iso(-14), createdAt: iso(-14) },
    { id: "measurement_6", userId: "user_athlete_1", heightCm: 168, weightKg: 67.8, waistCm: 74, measuredAt: iso(-7), createdAt: iso(-7) },
    { id: "measurement_7", userId: "user_athlete_2", heightCm: 182, weightKg: 86.2, waistCm: 90, measuredAt: iso(-35), createdAt: iso(-35) },
    { id: "measurement_8", userId: "user_athlete_2", heightCm: 182, weightKg: 85.7, waistCm: 89, measuredAt: iso(-21), createdAt: iso(-21) },
    { id: "measurement_9", userId: "user_athlete_2", heightCm: 182, weightKg: 84.6, waistCm: 88, measuredAt: iso(-7), createdAt: iso(-7) },
  ],
  nutritionProfiles: [
    {
      id: "nutrition_profile_1",
      userId: "user_athlete_1",
      goal: "maintain",
      activityLevel: "moderate",
      mealsPerDay: 5,
      targetKcal: 2250,
      proteinG: 135,
      carbsG: 255,
      fatG: 70,
      calculationMode: "auto",
      coachNotes: "Pidä arjen syöminen tasaisena treenipäivinä ja lisää hiilarit lounaalle.",
      dietaryFlags: [],
      allergies: [],
      createdBy: "user_admin_1",
      updatedBy: "user_admin_1",
      createdAt: iso(-10),
      updatedAt: iso(-2),
    },
  ],
  ingredientsCatalog: [
    {
      id: "ingredient_chicken",
      name: "Kanan rintafilee",
      source: "manual",
      ownerRole: "admin",
      createdBy: "user_admin_1",
      defaultPurchaseUnit: "kg",
      kcalPer100: 110,
      proteinPer100: 23.1,
      carbsPer100: 0,
      fatPer100: 1.2,
      createdAt: iso(-20),
      updatedAt: iso(-2),
    },
    {
      id: "ingredient_rice",
      name: "Jasmiiniriisi, kuiva",
      source: "manual",
      ownerRole: "admin",
      createdBy: "user_admin_1",
      defaultPurchaseUnit: "kg",
      kcalPer100: 356,
      proteinPer100: 7,
      carbsPer100: 78,
      fatPer100: 0.8,
      createdAt: iso(-20),
      updatedAt: iso(-2),
    },
    {
      id: "ingredient_broccoli",
      name: "Parsakaali",
      source: "manual",
      ownerRole: "admin",
      createdBy: "user_admin_1",
      defaultPurchaseUnit: "g",
      kcalPer100: 34,
      proteinPer100: 2.8,
      carbsPer100: 4.4,
      fatPer100: 0.4,
      createdAt: iso(-20),
      updatedAt: iso(-2),
    },
    {
      id: "ingredient_olive_oil",
      name: "Oliiviöljy",
      source: "manual",
      ownerRole: "admin",
      createdBy: "user_admin_1",
      defaultPurchaseUnit: "ml",
      kcalPer100: 884,
      proteinPer100: 0,
      carbsPer100: 0,
      fatPer100: 100,
      createdAt: iso(-20),
      updatedAt: iso(-2),
    },
    {
      id: "ingredient_salt",
      name: "Suola",
      source: "manual",
      ownerRole: "admin",
      createdBy: "user_admin_1",
      defaultPurchaseUnit: "g",
      kcalPer100: 0,
      proteinPer100: 0,
      carbsPer100: 0,
      fatPer100: 0,
      createdAt: iso(-20),
      updatedAt: iso(-2),
    },
    {
      id: "ingredient_pepper",
      name: "Mustapippuri",
      source: "manual",
      ownerRole: "admin",
      createdBy: "user_admin_1",
      defaultPurchaseUnit: "g",
      kcalPer100: 251,
      proteinPer100: 10.4,
      carbsPer100: 64,
      fatPer100: 3.3,
      createdAt: iso(-20),
      updatedAt: iso(-2),
    },
    {
      id: "ingredient_oats",
      name: "Kaurahiutale",
      source: "manual",
      ownerRole: "admin",
      createdBy: "user_admin_1",
      defaultPurchaseUnit: "kg",
      kcalPer100: 366,
      proteinPer100: 13,
      carbsPer100: 58.7,
      fatPer100: 7,
      createdAt: iso(-20),
      updatedAt: iso(-2),
    },
    {
      id: "ingredient_skyr",
      name: "Skyr maustamaton",
      source: "manual",
      ownerRole: "admin",
      createdBy: "user_admin_1",
      defaultPurchaseUnit: "pack",
      gramsPerUnit: 200,
      kcalPer100: 63,
      proteinPer100: 11,
      carbsPer100: 3.9,
      fatPer100: 0.2,
      createdAt: iso(-20),
      updatedAt: iso(-2),
    },
    {
      id: "ingredient_blueberries",
      name: "Mustikka",
      source: "manual",
      ownerRole: "admin",
      createdBy: "user_admin_1",
      defaultPurchaseUnit: "g",
      kcalPer100: 51,
      proteinPer100: 0.6,
      carbsPer100: 7.6,
      fatPer100: 0.6,
      createdAt: iso(-20),
      updatedAt: iso(-2),
    },
  ],
  recipes: [
    {
      id: "recipe_chicken_rice",
      name: "Kana-riisikulho",
      description: "Helppo lounas tai illallinen arkeen.",
      instructions: "Kypsennä riisi. Paista kana pannulla öljyssä ja lisää loppuvaiheessa parsakaali. Mausta suolalla ja pippurilla. Jaa kulhoihin.",
      mealTag: "lunch",
      dietaryFlags: [],
      allergies: [],
      ownerRole: "admin",
      createdBy: "user_admin_1",
      defaultServings: 4,
      minServings: 2,
      maxServings: 8,
      ingredients: [
        {
          id: "recipe_ingredient_1",
          ingredientId: "ingredient_chicken",
          ingredientName: "Kanan rintafilee",
          quantity: 600,
          unit: "g",
          normalizedQuantity: 600,
          ingredientRole: "main",
          scalingMode: "linear",
        },
        {
          id: "recipe_ingredient_2",
          ingredientId: "ingredient_rice",
          ingredientName: "Jasmiiniriisi, kuiva",
          quantity: 300,
          unit: "g",
          normalizedQuantity: 300,
          ingredientRole: "main",
          scalingMode: "linear",
        },
        {
          id: "recipe_ingredient_3",
          ingredientId: "ingredient_broccoli",
          ingredientName: "Parsakaali",
          quantity: 250,
          unit: "g",
          normalizedQuantity: 250,
          ingredientRole: "main",
          scalingMode: "linear",
        },
        {
          id: "recipe_ingredient_4",
          ingredientId: "ingredient_olive_oil",
          ingredientName: "Oliiviöljy",
          quantity: 15,
          unit: "ml",
          normalizedQuantity: 15,
          ingredientRole: "main",
          scalingMode: "linear",
        },
        {
          id: "recipe_ingredient_5",
          ingredientId: "ingredient_salt",
          ingredientName: "Suola",
          quantity: 5,
          unit: "g",
          displayQuantity: "1",
          displayUnit: "tl",
          normalizedQuantity: 5,
          ingredientRole: "spice",
          scalingMode: "fixed",
        },
        {
          id: "recipe_ingredient_6",
          ingredientId: "ingredient_pepper",
          ingredientName: "Mustapippuri",
          unit: "g",
          displayQuantity: "maun mukaan",
          displayUnit: "",
          ingredientRole: "spice",
          scalingMode: "text_only",
        },
      ],
      nutritionPerRecipe: {
        servings: 4,
        kcal: 1605,
        proteinG: 165.2,
        carbsG: 246.1,
        fatG: 22.2,
      },
      nutritionPerServing: {
        servings: 1,
        kcal: 401,
        proteinG: 41.3,
        carbsG: 61.5,
        fatG: 5.6,
      },
      createdAt: iso(-12),
      updatedAt: iso(-2),
    },
    {
      id: "recipe_skyr_oats",
      name: "Skyr-kaurakulho",
      description: "Nopea aamupala tai iltapala.",
      instructions: "Mittaa kaurahiutaleet ja skyr kulhoon. Lisää mustikat päälle. Sekoita ennen syömistä.",
      mealTag: "breakfast",
      dietaryFlags: [],
      allergies: [],
      ownerRole: "admin",
      createdBy: "user_admin_1",
      defaultServings: 1,
      minServings: 1,
      maxServings: 3,
      ingredients: [
        {
          id: "recipe_ingredient_7",
          ingredientId: "ingredient_oats",
          ingredientName: "Kaurahiutale",
          quantity: 60,
          unit: "g",
          normalizedQuantity: 60,
          ingredientRole: "main",
          scalingMode: "linear",
        },
        {
          id: "recipe_ingredient_8",
          ingredientId: "ingredient_skyr",
          ingredientName: "Skyr maustamaton",
          quantity: 200,
          unit: "g",
          normalizedQuantity: 200,
          ingredientRole: "main",
          scalingMode: "linear",
        },
        {
          id: "recipe_ingredient_9",
          ingredientId: "ingredient_blueberries",
          ingredientName: "Mustikka",
          quantity: 80,
          unit: "g",
          normalizedQuantity: 80,
          ingredientRole: "garnish",
          scalingMode: "linear",
        },
      ],
      nutritionPerRecipe: {
        servings: 1,
        kcal: 386,
        proteinG: 30.1,
        carbsG: 51.8,
        fatG: 4.8,
      },
      nutritionPerServing: {
        servings: 1,
        kcal: 386,
        proteinG: 30.1,
        carbsG: 51.8,
        fatG: 4.8,
      },
      createdAt: iso(-12),
      updatedAt: iso(-2),
    },
  ],
  mealPlanTemplates: [
    {
      id: "meal_template_1",
      name: "Tasapainoinen peruspaiva",
      description: "Helppo pohja treenaajan perusarkeen.",
      ownerRole: "admin",
      createdBy: "user_admin_1",
      items: [
        { id: "meal_template_item_1", mealTag: "breakfast", recipeId: "recipe_skyr_oats", sortOrder: 0 },
        { id: "meal_template_item_2", mealTag: "lunch", recipeId: "recipe_chicken_rice", sortOrder: 1 },
        { id: "meal_template_item_3", mealTag: "dinner", recipeId: "recipe_chicken_rice", sortOrder: 2 },
        { id: "meal_template_item_4", mealTag: "evening_snack", recipeId: "recipe_skyr_oats", sortOrder: 3 },
      ],
      createdAt: iso(-9),
      updatedAt: iso(-2),
    },
  ],
  assignedMealPlans: [
    {
      id: "assigned_meal_plan_1",
      athleteId: "user_athlete_1",
      templateId: "meal_template_1",
      assignedBy: "user_admin_1",
      name: "Tasapainoinen peruspaiva",
      items: [
        { id: "assigned_meal_plan_item_1", mealTag: "breakfast", recipeId: "recipe_skyr_oats", sortOrder: 0 },
        { id: "assigned_meal_plan_item_1b", mealTag: "breakfast", recipeId: "recipe_chicken_rice", sortOrder: 1 },
        { id: "assigned_meal_plan_item_1c", mealTag: "breakfast", recipeId: "recipe_skyr_oats", sortOrder: 2 },
        { id: "assigned_meal_plan_item_2", mealTag: "lunch", recipeId: "recipe_chicken_rice", sortOrder: 3 },
        { id: "assigned_meal_plan_item_2b", mealTag: "lunch", recipeId: "recipe_skyr_oats", sortOrder: 4 },
        { id: "assigned_meal_plan_item_3", mealTag: "dinner", recipeId: "recipe_chicken_rice", sortOrder: 5 },
        { id: "assigned_meal_plan_item_4", mealTag: "evening_snack", recipeId: "recipe_skyr_oats", sortOrder: 6 },
      ],
      active: true,
      assignedAt: iso(-3),
      updatedAt: iso(-2),
    },
  ],
  assignments: [
    {
      id: "assignment_1",
      coachId: "user_coach_1",
      athleteId: "user_athlete_1",
      active: true,
      createdAt: iso(-20),
    },
    {
      id: "assignment_2",
      coachId: "user_coach_1",
      athleteId: "user_athlete_2",
      active: true,
      createdAt: iso(-18),
    },
  ],
  exercises: defaultGlobalExercises,
  templates: [
    {
      id: "template_lower_1",
      coachId: "user_coach_1",
      title: "Voimapäivä A",
      description: "Alavartalon voimapainotteinen treeni viikon alkuun.",
      goal: "Perusvoima + liikeradan laatu",
      splitType: "lower",
      status: "published",
      blocks: [
        {
          id: "block_1",
          title: "Pääsarjat",
          note: "Nosta painoja vain, jos kaikki sarjat tuntuvat hallituilta.",
          exercises: [
            {
              id: "template_ex_1",
              exerciseId: "ex_back_squat",
              instruction: "Pidä 2s pysäytys alhaalla ensimmäisissä kahdessa sarjassa.",
              sets: [
                { id: "set_1", label: "1", targetReps: 5, targetLoad: 70, restSeconds: 120 },
                { id: "set_2", label: "2", targetReps: 5, targetLoad: 70, restSeconds: 120 },
                { id: "set_3", label: "3", targetReps: 5, targetLoad: 72.5, restSeconds: 150 },
              ],
            },
            {
              id: "template_ex_2",
              exerciseId: "ex_romanian_deadlift",
              instruction: "Laske 3 sekuntia alas.",
              sets: [
                { id: "set_4", label: "1", targetReps: 8, targetLoad: 55, restSeconds: 90 },
                { id: "set_5", label: "2", targetReps: 8, targetLoad: 55, restSeconds: 90 },
                { id: "set_6", label: "3", targetReps: 8, targetLoad: 57.5, restSeconds: 90 },
              ],
            },
            {
              id: "template_ex_7",
              exerciseId: "ex_leg_curl",
              instruction: "Purista takareisiä yläasennossa ja laske hallitusti alas.",
              sets: [
                { id: "set_19", label: "1", targetReps: 12, targetLoad: 30, restSeconds: 60 },
                { id: "set_20", label: "2", targetReps: 12, targetLoad: 30, restSeconds: 60 },
                { id: "set_21", label: "3", targetReps: 12, targetLoad: 32.5, restSeconds: 60 },
              ],
            },
            {
              id: "template_ex_8",
              exerciseId: "ex_calf_raise_standing",
              instruction: "Käy täydessä venytyksessä ja pysäytä hetkeksi yläasennossa.",
              sets: [
                { id: "set_22", label: "1", targetReps: 15, targetLoad: 20, restSeconds: 45 },
                { id: "set_23", label: "2", targetReps: 15, targetLoad: 20, restSeconds: 45 },
                { id: "set_24", label: "3", targetReps: 15, targetLoad: 25, restSeconds: 45 },
              ],
            },
          ],
        },
      ],
      createdAt: iso(-14),
      updatedAt: iso(-3),
      createdBy: "user_coach_1",
      updatedBy: "user_coach_1",
    },
    {
      id: "template_upper_1",
      coachId: "user_coach_1",
      title: "Ylävartalo B",
      description: "Työntö-veto -yhdistelmä progressiolla.",
      goal: "Lihaskestävyys ja kontrolli",
      splitType: "upper",
      status: "published",
      blocks: [
        {
          id: "block_2",
          title: "Työosio",
          exercises: [
            {
              id: "template_ex_3",
              exerciseId: "ex_bench_press",
              instruction: "Pidä 1 toisto varaa jokaisessa sarjassa.",
              sets: [
                { id: "set_7", label: "1", targetReps: 8, targetLoad: 45, restSeconds: 90 },
                { id: "set_8", label: "2", targetReps: 8, targetLoad: 45, restSeconds: 90 },
                { id: "set_9", label: "3", targetReps: 8, targetLoad: 47.5, restSeconds: 90 },
              ],
            },
            {
              id: "template_ex_4",
              exerciseId: "ex_row",
              instruction: "Pysäytä yläasennossa sekunti.",
              sets: [
                { id: "set_10", label: "1", targetReps: 10, targetLoad: 18, restSeconds: 60 },
                { id: "set_11", label: "2", targetReps: 10, targetLoad: 18, restSeconds: 60 },
                { id: "set_12", label: "3", targetReps: 10, targetLoad: 20, restSeconds: 60 },
              ],
            },
            {
              id: "template_ex_9",
              exerciseId: "ex_overhead_press",
              instruction: "Pidä keskivartalo tiukkana ja työnnä suoraan ylös.",
              sets: [
                { id: "set_25", label: "1", targetReps: 8, targetLoad: 25, restSeconds: 75 },
                { id: "set_26", label: "2", targetReps: 8, targetLoad: 25, restSeconds: 75 },
                { id: "set_27", label: "3", targetReps: 8, targetLoad: 27.5, restSeconds: 75 },
              ],
            },
            {
              id: "template_ex_10",
              exerciseId: "ex_lat_pulldown",
              instruction: "Vedä kyynärpäät alas ja taakse ilman nykäisyä.",
              sets: [
                { id: "set_28", label: "1", targetReps: 10, targetLoad: 40, restSeconds: 60 },
                { id: "set_29", label: "2", targetReps: 10, targetLoad: 40, restSeconds: 60 },
                { id: "set_30", label: "3", targetReps: 10, targetLoad: 45, restSeconds: 60 },
              ],
            },
          ],
        },
      ],
      createdAt: iso(-12),
      updatedAt: iso(-2),
      createdBy: "user_coach_1",
      updatedBy: "user_coach_1",
    },
    {
      id: "template_full_1",
      coachId: "user_coach_1",
      title: "Koko kroppa C",
      description: "Koko kehon kontrolli- ja tukivoimapäivä viikon loppuun.",
      goal: "Tasapaino + liikehallinta + kokonaiskuorma",
      splitType: "full_body",
      status: "published",
      blocks: [
        {
          id: "block_3",
          title: "Full body flow",
          exercises: [
            {
              id: "template_ex_5",
              exerciseId: "ex_split_squat",
              instruction: "Pidä lantio suorassa ja kontrolloi jokainen toisto.",
              sets: [
                { id: "set_13", label: "1", targetReps: 10, targetLoad: 14, restSeconds: 75 },
                { id: "set_14", label: "2", targetReps: 10, targetLoad: 14, restSeconds: 75 },
                { id: "set_15", label: "3", targetReps: 10, targetLoad: 16, restSeconds: 75 },
              ],
            },
            {
              id: "template_ex_6",
              exerciseId: "ex_plank",
              instruction: "Pidä keskivartalo aktiivisena koko sarjan ajan.",
              sets: [
                { id: "set_16", label: "1", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
                { id: "set_17", label: "2", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
                { id: "set_18", label: "3", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
              ],
            },
            {
              id: "template_ex_11",
              exerciseId: "ex_incline_db_press",
              instruction: "Pidä lavat tuettuina penkkiin ja työnnä tasaisesti ylös.",
              sets: [
                { id: "set_31", label: "1", targetReps: 10, targetLoad: 16, restSeconds: 75 },
                { id: "set_32", label: "2", targetReps: 10, targetLoad: 16, restSeconds: 75 },
                { id: "set_33", label: "3", targetReps: 10, targetLoad: 18, restSeconds: 75 },
              ],
            },
            {
              id: "template_ex_12",
              exerciseId: "ex_seated_cable_row",
              instruction: "Vedä kyynärpäät taakse ja pysäytä hetkeksi loppuasentoon.",
              sets: [
                { id: "set_34", label: "1", targetReps: 12, targetLoad: 35, restSeconds: 60 },
                { id: "set_35", label: "2", targetReps: 12, targetLoad: 35, restSeconds: 60 },
                { id: "set_36", label: "3", targetReps: 12, targetLoad: 40, restSeconds: 60 },
              ],
            },
          ],
        },
      ],
      createdAt: iso(-10),
      updatedAt: iso(-2),
      createdBy: "user_coach_1",
      updatedBy: "user_coach_1",
    },
  ],
  plans: [
    {
      id: "plan_1",
      coachId: "user_coach_1",
      athleteId: "user_athlete_1",
      title: "Sara 4 viikon voimaohjelma",
      workouts: [
        {
          id: "program_workout_upper_1",
          name: "Ylävartalo B",
          splitType: "upper",
          defaultRestSeconds: 90,
          exercises: [
            {
              id: "program_ex_1",
              exerciseId: "ex_bench_press",
              exerciseName: "Penkkipunnerrus",
              muscleGroup: "chest",
              instruction: "Pidä 1 toisto varaa jokaisessa sarjassa.",
              sets: [
                { id: "program_set_1", label: "1", targetReps: 8, targetLoad: 45, restSeconds: 90 },
                { id: "program_set_2", label: "2", targetReps: 8, targetLoad: 45, restSeconds: 90 },
                { id: "program_set_3", label: "3", targetReps: 8, targetLoad: 47.5, restSeconds: 90 },
              ],
            },
            {
              id: "program_ex_2",
              exerciseId: "ex_row",
              exerciseName: "Kulmasoutu",
              muscleGroup: "back",
              instruction: "Pysäytä yläasennossa sekunti.",
              sets: [
                { id: "program_set_4", label: "1", targetReps: 10, targetLoad: 18, restSeconds: 60 },
                { id: "program_set_5", label: "2", targetReps: 10, targetLoad: 18, restSeconds: 60 },
                { id: "program_set_6", label: "3", targetReps: 10, targetLoad: 20, restSeconds: 60 },
              ],
            },
            {
              id: "program_ex_7",
              exerciseId: "ex_overhead_press",
              exerciseName: "Pystypunnerrus tangolla",
              muscleGroup: "shoulders",
              instruction: "Pidä keskivartalo tiukkana ja työnnä suoraan ylös.",
              sets: [
                { id: "program_set_19", label: "1", targetReps: 8, targetLoad: 25, restSeconds: 75 },
                { id: "program_set_20", label: "2", targetReps: 8, targetLoad: 25, restSeconds: 75 },
                { id: "program_set_21", label: "3", targetReps: 8, targetLoad: 27.5, restSeconds: 75 },
              ],
            },
            {
              id: "program_ex_8",
              exerciseId: "ex_lat_pulldown",
              exerciseName: "Ylätalja",
              muscleGroup: "back",
              instruction: "Vedä kyynärpäät alas ja taakse ilman nykäisyä.",
              sets: [
                { id: "program_set_22", label: "1", targetReps: 10, targetLoad: 40, restSeconds: 60 },
                { id: "program_set_23", label: "2", targetReps: 10, targetLoad: 40, restSeconds: 60 },
                { id: "program_set_24", label: "3", targetReps: 10, targetLoad: 45, restSeconds: 60 },
              ],
            },
          ],
        },
        {
          id: "program_workout_lower_1",
          name: "Voimapäivä A",
          splitType: "lower",
          defaultRestSeconds: 120,
          exercises: [
            {
              id: "program_ex_3",
              exerciseId: "ex_back_squat",
              exerciseName: "Takakyykky",
              muscleGroup: "legs",
              instruction: "Pidä 2s pysäytys alhaalla ensimmäisissä kahdessa sarjassa.",
              sets: [
                { id: "program_set_7", label: "1", targetReps: 5, targetLoad: 70, restSeconds: 120 },
                { id: "program_set_8", label: "2", targetReps: 5, targetLoad: 70, restSeconds: 120 },
                { id: "program_set_9", label: "3", targetReps: 5, targetLoad: 72.5, restSeconds: 150 },
              ],
            },
            {
              id: "program_ex_4",
              exerciseId: "ex_romanian_deadlift",
              exerciseName: "Romanialainen maastaveto",
              muscleGroup: "legs",
              instruction: "Laske 3 sekuntia alas.",
              sets: [
                { id: "program_set_10", label: "1", targetReps: 8, targetLoad: 55, restSeconds: 90 },
                { id: "program_set_11", label: "2", targetReps: 8, targetLoad: 55, restSeconds: 90 },
                { id: "program_set_12", label: "3", targetReps: 8, targetLoad: 57.5, restSeconds: 90 },
              ],
            },
            {
              id: "program_ex_9",
              exerciseId: "ex_leg_curl",
              exerciseName: "Takareisikoukistus",
              muscleGroup: "legs",
              instruction: "Purista takareisiä yläasennossa ja laske hallitusti alas.",
              sets: [
                { id: "program_set_25", label: "1", targetReps: 12, targetLoad: 30, restSeconds: 60 },
                { id: "program_set_26", label: "2", targetReps: 12, targetLoad: 30, restSeconds: 60 },
                { id: "program_set_27", label: "3", targetReps: 12, targetLoad: 32.5, restSeconds: 60 },
              ],
            },
            {
              id: "program_ex_10",
              exerciseId: "ex_calf_raise_standing",
              exerciseName: "Pohjenousu seisten",
              muscleGroup: "legs",
              instruction: "Käy täydessä venytyksessä ja pysäytä hetkeksi yläasennossa.",
              sets: [
                { id: "program_set_28", label: "1", targetReps: 15, targetLoad: 20, restSeconds: 45 },
                { id: "program_set_29", label: "2", targetReps: 15, targetLoad: 20, restSeconds: 45 },
                { id: "program_set_30", label: "3", targetReps: 15, targetLoad: 25, restSeconds: 45 },
              ],
            },
          ],
        },
        {
          id: "program_workout_full_1",
          name: "Koko kroppa C",
          splitType: "full_body",
          defaultRestSeconds: 75,
          exercises: [
            {
              id: "program_ex_5",
              exerciseId: "ex_split_squat",
              exerciseName: "Bulgarialainen askelkyykky",
              muscleGroup: "legs",
              instruction: "Pidä lantio suorassa ja kontrolloi jokainen toisto.",
              sets: [
                { id: "program_set_13", label: "1", targetReps: 10, targetLoad: 14, restSeconds: 75 },
                { id: "program_set_14", label: "2", targetReps: 10, targetLoad: 14, restSeconds: 75 },
                { id: "program_set_15", label: "3", targetReps: 10, targetLoad: 16, restSeconds: 75 },
              ],
            },
            {
              id: "program_ex_6",
              exerciseId: "ex_plank",
              exerciseName: "Lankku",
              muscleGroup: "abs",
              instruction: "Pidä keskivartalo aktiivisena koko sarjan ajan.",
              sets: [
                { id: "program_set_16", label: "1", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
                { id: "program_set_17", label: "2", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
                { id: "program_set_18", label: "3", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
              ],
            },
            {
              id: "program_ex_11",
              exerciseId: "ex_incline_db_press",
              exerciseName: "Vinopenkki käsipainoilla",
              muscleGroup: "chest",
              instruction: "Pidä lavat tuettuina penkkiin ja työnnä tasaisesti ylös.",
              sets: [
                { id: "program_set_31", label: "1", targetReps: 10, targetLoad: 16, restSeconds: 75 },
                { id: "program_set_32", label: "2", targetReps: 10, targetLoad: 16, restSeconds: 75 },
                { id: "program_set_33", label: "3", targetReps: 10, targetLoad: 18, restSeconds: 75 },
              ],
            },
            {
              id: "program_ex_12",
              exerciseId: "ex_seated_cable_row",
              exerciseName: "Istuva soutu taljassa",
              muscleGroup: "back",
              instruction: "Vedä kyynärpäät taakse ja pysäytä hetkeksi loppuasentoon.",
              sets: [
                { id: "program_set_34", label: "1", targetReps: 12, targetLoad: 35, restSeconds: 60 },
                { id: "program_set_35", label: "2", targetReps: 12, targetLoad: 35, restSeconds: 60 },
                { id: "program_set_36", label: "3", targetReps: 12, targetLoad: 40, restSeconds: 60 },
              ],
            },
          ],
        },
      ],
      startDate: iso(-7),
      weekCount: 4,
      createdAt: iso(-7),
      updatedAt: iso(-2),
    },
  ],
  scheduledWorkouts: [
    {
      id: "scheduled_5",
      trainingPlanId: "plan_1",
      templateId: "template_upper_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      title: "Ylävartalo B",
      scheduledDate: iso(-8),
      status: "completed",
      createdAt: iso(-10),
      updatedAt: iso(-8),
      completedAt: iso(-8),
    },
    {
      id: "scheduled_1",
      trainingPlanId: "plan_1",
      templateId: "template_lower_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      title: "Voimapäivä A",
      scheduledDate: iso(-1),
      status: "completed",
      createdAt: iso(-4),
      updatedAt: iso(-1),
      completedAt: iso(-1),
    },
    {
      id: "scheduled_2",
      trainingPlanId: "plan_1",
      // Kesken oleva treeni linkitetään ohjelman treeniin (ei vanhaan templateen), jotta se
      // näkyy treenilistassa ja sen voi jatkaa loppuun myös lokaalissa demotilassa.
      programWorkoutId: "program_workout_upper_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      title: "Ylävartalo B",
      scheduledDate: iso(0),
      status: "in_progress",
      createdAt: iso(-3),
      updatedAt: iso(0),
    },
    {
      id: "scheduled_3",
      templateId: "template_lower_1",
      athleteId: "user_athlete_2",
      coachId: "user_coach_1",
      title: "Voimapäivä A",
      scheduledDate: iso(1),
      status: "cancelled",
      createdAt: iso(-2),
      updatedAt: iso(-2),
    },
    {
      id: "scheduled_4",
      trainingPlanId: "plan_1",
      templateId: "template_full_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      title: "Koko kroppa C",
      scheduledDate: iso(2),
      status: "cancelled",
      createdAt: iso(-2),
      updatedAt: iso(-2),
    },
  ],
  sessions: [
    {
      id: "session_3",
      scheduledWorkoutId: "scheduled_5",
      athleteId: "user_athlete_1",
      startedAt: iso(-8),
      completedAt: iso(-8),
      updatedAt: iso(-8),
      energyLevel: 4,
      setLogs: [
        {
          id: "log_9",
          scheduledWorkoutId: "scheduled_5",
          templateExerciseId: "template_ex_3",
          setId: "set_7",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "1",
          targetReps: 8,
          targetLoad: 45,
          actualReps: 8,
          actualLoad: 45,
          done: true,
        },
        {
          id: "log_10",
          scheduledWorkoutId: "scheduled_5",
          templateExerciseId: "template_ex_3",
          setId: "set_8",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "2",
          targetReps: 8,
          targetLoad: 45,
          actualReps: 8,
          actualLoad: 45,
          done: true,
        },
        {
          id: "log_11",
          scheduledWorkoutId: "scheduled_5",
          templateExerciseId: "template_ex_4",
          setId: "set_10",
          exerciseId: "ex_row",
          exerciseName: "Kulmasoutu",
          setLabel: "1",
          targetReps: 10,
          targetLoad: 18,
          actualReps: 10,
          actualLoad: 18,
          done: true,
        },
      ],
    },
    {
      id: "session_1",
      scheduledWorkoutId: "scheduled_1",
      athleteId: "user_athlete_1",
      startedAt: iso(-1),
      completedAt: iso(-1),
      updatedAt: iso(-1),
      energyLevel: 4,
      setLogs: [
        {
          id: "log_1",
          scheduledWorkoutId: "scheduled_1",
          templateExerciseId: "template_ex_1",
          setId: "set_1",
          exerciseId: "ex_back_squat",
          exerciseName: "Takakyykky",
          setLabel: "1",
          targetReps: 5,
          targetLoad: 70,
          actualReps: 5,
          actualLoad: 70,
          done: true,
        },
        {
          id: "log_2",
          scheduledWorkoutId: "scheduled_1",
          templateExerciseId: "template_ex_1",
          setId: "set_2",
          exerciseId: "ex_back_squat",
          exerciseName: "Takakyykky",
          setLabel: "2",
          targetReps: 5,
          targetLoad: 70,
          actualReps: 5,
          actualLoad: 70,
          done: true,
        },
      ],
    },
    {
      id: "session_2",
      scheduledWorkoutId: "scheduled_2",
      athleteId: "user_athlete_1",
      startedAt: iso(0),
      updatedAt: iso(0),
      energyLevel: 3,
      setLogs: [
        {
          id: "log_3",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "program_ex_1",
          setId: "program_set_1",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "1",
          targetReps: 8,
          targetLoad: 45,
          targetRestSeconds: 90,
          actualReps: 8,
          actualLoad: 45,
          done: true,
        },
        {
          id: "log_4",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "program_ex_1",
          setId: "program_set_2",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "2",
          targetReps: 8,
          targetLoad: 45,
          targetRestSeconds: 90,
          actualReps: 8,
          actualLoad: 45,
          done: false,
        },
        {
          id: "log_5",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "program_ex_1",
          setId: "program_set_3",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "3",
          targetReps: 8,
          targetLoad: 47.5,
          targetRestSeconds: 90,
          actualReps: 8,
          actualLoad: 47.5,
          done: false,
        },
        {
          id: "log_6",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "program_ex_2",
          setId: "program_set_4",
          exerciseId: "ex_row",
          exerciseName: "Kulmasoutu",
          setLabel: "1",
          targetReps: 10,
          targetLoad: 18,
          targetRestSeconds: 60,
          actualReps: 10,
          actualLoad: 18,
          done: false,
        },
        {
          id: "log_7",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "program_ex_2",
          setId: "program_set_5",
          exerciseId: "ex_row",
          exerciseName: "Kulmasoutu",
          setLabel: "2",
          targetReps: 10,
          targetLoad: 18,
          targetRestSeconds: 60,
          actualReps: 10,
          actualLoad: 18,
          done: false,
        },
        {
          id: "log_8",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "program_ex_2",
          setId: "program_set_6",
          exerciseId: "ex_row",
          exerciseName: "Kulmasoutu",
          setLabel: "3",
          targetReps: 10,
          targetLoad: 20,
          targetRestSeconds: 60,
          actualReps: 10,
          actualLoad: 20,
          done: false,
        },
        {
          id: "log_12",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "program_ex_7",
          setId: "program_set_19",
          exerciseId: "ex_overhead_press",
          exerciseName: "Pystypunnerrus tangolla",
          setLabel: "1",
          targetReps: 8,
          targetLoad: 25,
          targetRestSeconds: 75,
          actualReps: 8,
          actualLoad: 25,
          done: false,
        },
        {
          id: "log_13",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "program_ex_7",
          setId: "program_set_20",
          exerciseId: "ex_overhead_press",
          exerciseName: "Pystypunnerrus tangolla",
          setLabel: "2",
          targetReps: 8,
          targetLoad: 25,
          targetRestSeconds: 75,
          actualReps: 8,
          actualLoad: 25,
          done: false,
        },
        {
          id: "log_14",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "program_ex_7",
          setId: "program_set_21",
          exerciseId: "ex_overhead_press",
          exerciseName: "Pystypunnerrus tangolla",
          setLabel: "3",
          targetReps: 8,
          targetLoad: 27.5,
          targetRestSeconds: 75,
          actualReps: 8,
          actualLoad: 27.5,
          done: false,
        },
        {
          id: "log_15",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "program_ex_8",
          setId: "program_set_22",
          exerciseId: "ex_lat_pulldown",
          exerciseName: "Ylätalja",
          setLabel: "1",
          targetReps: 10,
          targetLoad: 40,
          targetRestSeconds: 60,
          actualReps: 10,
          actualLoad: 40,
          done: false,
        },
        {
          id: "log_16",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "program_ex_8",
          setId: "program_set_23",
          exerciseId: "ex_lat_pulldown",
          exerciseName: "Ylätalja",
          setLabel: "2",
          targetReps: 10,
          targetLoad: 40,
          targetRestSeconds: 60,
          actualReps: 10,
          actualLoad: 40,
          done: false,
        },
        {
          id: "log_17",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "program_ex_8",
          setId: "program_set_24",
          exerciseId: "ex_lat_pulldown",
          exerciseName: "Ylätalja",
          setLabel: "3",
          targetReps: 10,
          targetLoad: 45,
          targetRestSeconds: 60,
          actualReps: 10,
          actualLoad: 45,
          done: false,
        },
      ],
    },
  ],
  notes: [
    {
      id: "note_1",
      sessionId: "session_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      body: "Takakyykky tuntui vakaalta. Voidaan nostaa 2,5 kg ensi viikolla.",
      createdAt: iso(-1),
      updatedAt: iso(-1),
    },
  ],
  conversationEntries: [
    {
      id: "conversation_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      authorUserId: "user_athlete_1",
      authorRole: "athlete",
      type: "comment",
      body: "Kyykyn viimeinen sarja oli jo aika raskas, mutta tekniikka pysyi kasassa.",
      contextType: "workout",
      contextId: "scheduled_1",
      contextLabel: "Alakroppa 1",
      createdAt: iso(-1),
      readByUserIds: ["user_athlete_1"],
    },
    {
      id: "conversation_2",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      authorUserId: "user_coach_1",
      authorRole: "coach",
      type: "comment",
      body: "Hyvä huomio. Pidetään ensi viikolla sama kuorma ja haetaan puhtaampi loppu.",
      contextType: "workout",
      contextId: "scheduled_1",
      contextLabel: "Alakroppa 1",
      createdAt: iso(0),
      readByUserIds: ["user_coach_1"],
    },
  ],
  invites: [
    {
      id: "invite_1",
      token: "join-noora-demo",
      email: "noora@rooki.fit",
      role: "athlete",
      invitedBy: "user_coach_1",
      coachId: "user_coach_1",
      status: "pending",
      createdAt: iso(-1),
      expiresAt: iso(6),
    },
  ],
  passwordResetRequests: [],
};
