import type { AppState } from "@/lib/types";

const today = new Date();
const iso = (offsetDays: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + offsetDays);
  date.setHours(8, 0, 0, 0);
  return date.toISOString();
};

export const defaultGlobalExercises: AppState["exercises"] = [
  {
    id: "ex_back_squat",
    name: "Takakyykky",
    category: "Alavartalo",
    equipment: "Levantotanko",
    cue: "Pidä keskivartalo tiukkana ja aja jaloilla lattiaa vasten.",
    scope: "global",
  },
  {
    id: "ex_front_squat",
    name: "Etukyykky",
    category: "Alavartalo",
    equipment: "Levantotanko",
    cue: "Pidä kyynärpäät ylhäällä ja rintakehä avoinna.",
    scope: "global",
  },
  {
    id: "ex_goblet_squat",
    name: "Goblet-kyykky",
    category: "Alavartalo",
    equipment: "Käsipaino / Kahvakuula",
    cue: "Paina polvia ulos ja pidä kantapäät lattiassa.",
    scope: "global",
  },
  {
    id: "ex_leg_press",
    name: "Jalkaprässi",
    category: "Alavartalo",
    equipment: "Jalkaprässi",
    cue: "Kontrolloi alasmeno ja työnnä tasaisesti koko jalkapohjalla.",
    scope: "global",
  },
  {
    id: "ex_hack_squat",
    name: "Hack-kyykky",
    category: "Alavartalo",
    equipment: "Hack-laite",
    cue: "Pidä selkä tuettuna ja liike hallittuna koko matkalla.",
    scope: "global",
  },
  {
    id: "ex_split_squat",
    name: "Bulgarialainen askelkyykky",
    category: "Alavartalo",
    equipment: "Käsipainot",
    cue: "Laske hallitusti ja pidä paino etujalalla.",
    scope: "global",
  },
  {
    id: "ex_walking_lunge",
    name: "Kävelyaskelkyykky",
    category: "Alavartalo",
    equipment: "Käsipainot",
    cue: "Pidä vartalo pystyssä ja askelpituus tasaisena.",
    scope: "global",
  },
  {
    id: "ex_step_up",
    name: "Step-up",
    category: "Alavartalo",
    equipment: "Boksi + käsipainot",
    cue: "Paina ylös etujalan kautta ilman ponnistusta takajalalla.",
    scope: "global",
  },
  {
    id: "ex_romanian_deadlift",
    name: "Romanialainen maastaveto",
    category: "Takaketju",
    equipment: "Levantotanko",
    cue: "Vie lantio taakse ja pidä tanko lähellä vartaloa.",
    scope: "global",
  },
  {
    id: "ex_deadlift",
    name: "Maastaveto",
    category: "Takaketju",
    equipment: "Levantotanko",
    cue: "Vedä tanko lähellä sääriä ja lukitse selkä neutraaliksi.",
    scope: "global",
  },
  {
    id: "ex_sumo_deadlift",
    name: "Sumomaastaveto",
    category: "Takaketju",
    equipment: "Levantotanko",
    cue: "Avaa polvet varpaiden suuntaan ja työnnä lattiaa sivuille.",
    scope: "global",
  },
  {
    id: "ex_good_morning",
    name: "Good morning",
    category: "Takaketju",
    equipment: "Levantotanko",
    cue: "Pidä polvissa kevyt koukku ja taivuta lantiosta, ei selästä.",
    scope: "global",
  },
  {
    id: "ex_hip_thrust",
    name: "Hip thrust",
    category: "Pakarat",
    equipment: "Penkki + tanko",
    cue: "Purista pakarat yläasennossa ja pidä kylkiluut alhaalla.",
    scope: "global",
  },
  {
    id: "ex_glute_bridge",
    name: "Glute bridge",
    category: "Pakarat",
    equipment: "Kehonpaino / tanko",
    cue: "Nosta lantio linjaan ja pidä jännitys pakaroissa.",
    scope: "global",
  },
  {
    id: "ex_leg_curl",
    name: "Takareisikoukistus",
    category: "Alavartalo",
    equipment: "Leg curl -laite",
    cue: "Pidä lantio tuettuna ja tee liike ilman heilautusta.",
    scope: "global",
  },
  {
    id: "ex_leg_extension",
    name: "Jalanojennus",
    category: "Alavartalo",
    equipment: "Leg extension -laite",
    cue: "Pysäytä hetkeksi yläasennossa ja laske hallitusti.",
    scope: "global",
  },
  {
    id: "ex_calf_raise_standing",
    name: "Pohjenousu seisten",
    category: "Alavartalo",
    equipment: "Pohjelaite / käsipainot",
    cue: "Käy täydessä venytyksessä ja nouse varpaille loppuun asti.",
    scope: "global",
  },
  {
    id: "ex_calf_raise_seated",
    name: "Pohjenousu istuen",
    category: "Alavartalo",
    equipment: "Istuva pohjelaite",
    cue: "Pidä tempo rauhallisena ja hakeudu täyteen liikerataan.",
    scope: "global",
  },
  {
    id: "ex_hip_abduction_machine",
    name: "Lonkan loitonnus laitteessa",
    category: "Pakarat",
    equipment: "Abductor-laite",
    cue: "Pidä lantio vakaana ja avaa jalat hallitusti ulos.",
    scope: "global",
  },
  {
    id: "ex_hip_adduction_machine",
    name: "Lonkan lähennys laitteessa",
    category: "Alavartalo",
    equipment: "Adductor-laite",
    cue: "Purista jalat yhteen hallitusti ilman nykäisyä.",
    scope: "global",
  },
  {
    id: "ex_bench_press",
    name: "Penkkipunnerrus",
    category: "Rinta",
    equipment: "Penkki + tanko",
    cue: "Vedä lapaluut yhteen ja pidä jalat aktiivisina.",
    scope: "global",
  },
  {
    id: "ex_incline_bench_press",
    name: "Vinopenkki tangolla",
    category: "Rinta",
    equipment: "Vinopenkki + tanko",
    cue: "Pidä liikerata hallittuna ja kyynärpäät hieman vartalon edessä.",
    scope: "global",
  },
  {
    id: "ex_decline_bench_press",
    name: "Alavinopenkki tangolla",
    category: "Rinta",
    equipment: "Alavinopenkki + tanko",
    cue: "Pidä lapatuet koko sarjan ajan.",
    scope: "global",
  },
  {
    id: "ex_db_bench_press",
    name: "Käsipainopenkki",
    category: "Rinta",
    equipment: "Penkki + käsipainot",
    cue: "Laske käsipainot kontrolloidusti ja työnnä ylös kaarella.",
    scope: "global",
  },
  {
    id: "ex_incline_db_press",
    name: "Vinopenkki käsipainoilla",
    category: "Rinta",
    equipment: "Vinopenkki + käsipainot",
    cue: "Pidä olkapäät alhaalla ja liike vakaana.",
    scope: "global",
  },
  {
    id: "ex_chest_fly_db",
    name: "Rintafly käsipainoilla",
    category: "Rinta",
    equipment: "Penkki + käsipainot",
    cue: "Säilytä kevyt kyynärkulma ja keskity venytykseen.",
    scope: "global",
  },
  {
    id: "ex_cable_fly",
    name: "Taljafly",
    category: "Rinta",
    equipment: "Talja",
    cue: "Pidä rintakehä ylhäällä ja vie kädet yhteen hallitusti.",
    scope: "global",
  },
  {
    id: "ex_pec_deck",
    name: "Pec deck",
    category: "Rinta",
    equipment: "Pec deck -laite",
    cue: "Purista rintaa keskiasennossa ja palauta hitaasti.",
    scope: "global",
  },
  {
    id: "ex_push_up",
    name: "Punnerrus",
    category: "Rinta",
    equipment: "Kehonpaino",
    cue: "Pidä vartalo linjassa ja liike täydessä kontrollissa.",
    scope: "global",
  },
  {
    id: "ex_dips",
    name: "Dippi",
    category: "Rinta / ojentajat",
    equipment: "Dippiteline",
    cue: "Pidä hartiat alhaalla ja kyynärpäät hallinnassa.",
    scope: "global",
  },
  {
    id: "ex_overhead_press",
    name: "Pystypunnerrus tangolla",
    category: "Hartiat",
    equipment: "Levantotanko",
    cue: "Purista pakarat ja vältä alaselän notkoa.",
    scope: "global",
  },
  {
    id: "ex_seated_db_press",
    name: "Istuva pystypunnerrus käsipainoilla",
    category: "Hartiat",
    equipment: "Penkki + käsipainot",
    cue: "Pidä kyynärpäät ranteiden alla koko liikkeen ajan.",
    scope: "global",
  },
  {
    id: "ex_arnold_press",
    name: "Arnold press",
    category: "Hartiat",
    equipment: "Käsipainot",
    cue: "Kierrä kädet hallitusti ja pidä liike pehmeänä.",
    scope: "global",
  },
  {
    id: "ex_lateral_raise",
    name: "Vipunosto sivulle",
    category: "Hartiat",
    equipment: "Käsipainot / talja",
    cue: "Nosta kyynärpäät johtavana ja vältä vauhdinottoa.",
    scope: "global",
  },
  {
    id: "ex_front_raise",
    name: "Vipunosto eteen",
    category: "Hartiat",
    equipment: "Käsipainot / levypaino",
    cue: "Pidä keskivartalo vakaana ja nosta hartiat rentoina.",
    scope: "global",
  },
  {
    id: "ex_rear_delt_fly",
    name: "Takaolkapääfly",
    category: "Hartiat",
    equipment: "Käsipainot / pec deck",
    cue: "Avaa kädet sivuille ja pidä yläselkä aktiivisena.",
    scope: "global",
  },
  {
    id: "ex_upright_row",
    name: "Pystysoutu",
    category: "Hartiat",
    equipment: "Tanko / käsipainot",
    cue: "Vedä kyynärpäät ylöspäin hallitusti ilman nykäisyä.",
    scope: "global",
  },
  {
    id: "ex_row",
    name: "Kulmasoutu",
    category: "Selkä",
    equipment: "Käsipainot",
    cue: "Pidä vartalo vakaana ja vedä kyynärpäät kohti lantiota.",
    scope: "global",
  },
  {
    id: "ex_barbell_row",
    name: "Kulmasoutu tangolla",
    category: "Selkä",
    equipment: "Levantotanko",
    cue: "Pidä selkä neutraalina ja vedä tanko alavatsalle.",
    scope: "global",
  },
  {
    id: "ex_chest_supported_row",
    name: "Rintasoutu penkiltä",
    category: "Selkä",
    equipment: "Vinopenkki + käsipainot",
    cue: "Pidä rintatuki kiinni penkissä ja vedä lavat yhteen.",
    scope: "global",
  },
  {
    id: "ex_seated_cable_row",
    name: "Istuva soutu taljassa",
    category: "Selkä",
    equipment: "Talja",
    cue: "Vedä kahva navan suuntaan ja palauta kontrolloidusti.",
    scope: "global",
  },
  {
    id: "ex_low_cable_row",
    name: "Alatalja",
    category: "Selkä",
    equipment: "Alatalja",
    cue: "Pidä rintakehä ylhäällä, vedä kyynärpäät taakse ja jarruta palautus.",
    scope: "global",
  },
  {
    id: "ex_lat_pulldown",
    name: "Ylätalja",
    category: "Selkä",
    equipment: "Ylätalja",
    cue: "Vedä kyynärpäät alas ja taakse, älä nykäise.",
    scope: "global",
  },
  {
    id: "ex_pull_up",
    name: "Leuanveto myötäotteella",
    category: "Selkä",
    equipment: "Leuanvetotanko",
    cue: "Aloita lapojen aktivoinnilla ja vedä rinta kohti tankoa.",
    scope: "global",
  },
  {
    id: "ex_chin_up",
    name: "Leuanveto vastaotteella",
    category: "Selkä / hauis",
    equipment: "Leuanvetotanko",
    cue: "Pidä keskivartalo tiukkana ja vältä keinumista.",
    scope: "global",
  },
  {
    id: "ex_single_arm_cable_row",
    name: "Yhden käden soutu taljassa",
    category: "Selkä",
    equipment: "Talja",
    cue: "Pidä lantio vakaana ja vedä kyynärpää taakse.",
    scope: "global",
  },
  {
    id: "ex_face_pull",
    name: "Face pull",
    category: "Yläselkä",
    equipment: "Talja + köysi",
    cue: "Vedä köysi kasvojen suuntaan ja kierrä peukalot taakse.",
    scope: "global",
  },
  {
    id: "ex_shrug",
    name: "Hartiannosto",
    category: "Yläselkä",
    equipment: "Käsipainot / tanko",
    cue: "Nosta hartiat suoraan ylös ja laske hitaasti.",
    scope: "global",
  },
  {
    id: "ex_straight_arm_pulldown",
    name: "Suorin käsin ylätaljaveto",
    category: "Selkä",
    equipment: "Talja",
    cue: "Pidä kyynärpäissä kevyt kulma ja vedä käsivarret alas.",
    scope: "global",
  },
  {
    id: "ex_close_grip_bench_press",
    name: "Kapea penkkipunnerrus",
    category: "Ojentajat",
    equipment: "Penkki + tanko",
    cue: "Pidä kyynärpäät lähellä vartaloa ja liike kontrollissa.",
    scope: "global",
  },
  {
    id: "ex_tricep_pushdown",
    name: "Ojentajapunnerrus taljassa",
    category: "Ojentajat",
    equipment: "Talja",
    cue: "Lukitse kyynärpäät kylkiin ja ojenna loppuun asti.",
    scope: "global",
  },
  {
    id: "ex_overhead_tricep_extension",
    name: "Ojentaja pään yli",
    category: "Ojentajat",
    equipment: "Köysitalja / käsipaino",
    cue: "Pidä yläkädet paikallaan ja venytä ojentaja kunnolla.",
    scope: "global",
  },
  {
    id: "ex_skullcrusher",
    name: "Ranskalainen punnerrus",
    category: "Ojentajat",
    equipment: "EZ-tanko / käsipainot",
    cue: "Pidä kyynärpäät osoittamassa ylös ja liike hallittuna.",
    scope: "global",
  },
  {
    id: "ex_barbell_curl",
    name: "Hauiskääntö tangolla",
    category: "Hauis",
    equipment: "EZ-tanko / suora tanko",
    cue: "Pidä kyynärpäät paikallaan ja vältä vartalon heijausta.",
    scope: "global",
  },
  {
    id: "ex_db_curl",
    name: "Hauiskääntö käsipainoilla",
    category: "Hauis",
    equipment: "Käsipainot",
    cue: "Kierrä kämmenet ylösnousussa ja laske hitaasti.",
    scope: "global",
  },
  {
    id: "ex_hammer_curl",
    name: "Vasarahauiskääntö",
    category: "Hauis",
    equipment: "Käsipainot",
    cue: "Pidä ranteet neutraalina ja kyynärpäät kyljessä.",
    scope: "global",
  },
  {
    id: "ex_preacher_curl",
    name: "Scott-hauiskääntö",
    category: "Hauis",
    equipment: "Scott-penkki",
    cue: "Pidä olkavarsi tukevasti padissa ja tee täysi liikerata.",
    scope: "global",
  },
  {
    id: "ex_cable_curl",
    name: "Hauiskääntö taljassa",
    category: "Hauis",
    equipment: "Talja",
    cue: "Pidä jännitys koko liikkeen ajan.",
    scope: "global",
  },
  {
    id: "ex_plank",
    name: "Lankku",
    category: "Core",
    equipment: "Kehonpaino",
    cue: "Purista pakarat ja pidä kyljet aktiivisina.",
    scope: "global",
  },
  {
    id: "ex_side_plank",
    name: "Sivulankku",
    category: "Core",
    equipment: "Kehonpaino",
    cue: "Pidä lantio ylhäällä ja vartalo suorassa linjassa.",
    scope: "global",
  },
  {
    id: "ex_dead_bug",
    name: "Dead bug",
    category: "Core",
    equipment: "Kehonpaino",
    cue: "Pidä alaselkä kevyesti lattiaa vasten koko liikkeen ajan.",
    scope: "global",
  },
  {
    id: "ex_ab_wheel",
    name: "Ab wheel roll-out",
    category: "Core",
    equipment: "Ab wheel",
    cue: "Vie rulla eteen hallitusti säilyttäen keskivartalon jännitys.",
    scope: "global",
  },
  {
    id: "ex_hanging_leg_raise",
    name: "Jalkojen nosto roikkuen",
    category: "Core",
    equipment: "Leuanvetotanko",
    cue: "Nosta jalat ilman heiluriliikettä.",
    scope: "global",
  },
  {
    id: "ex_cable_crunch",
    name: "Vatsarutistus taljassa",
    category: "Core",
    equipment: "Talja",
    cue: "Pyöristä yläselkä hallitusti ja pidä lantio paikallaan.",
    scope: "global",
  },
  {
    id: "ex_russian_twist",
    name: "Russian twist",
    category: "Core",
    equipment: "Levy / käsipaino",
    cue: "Kierrä rintarankaa, älä vain heilauta käsiä.",
    scope: "global",
  },
  {
    id: "ex_pallof_press",
    name: "Pallof press",
    category: "Core",
    equipment: "Talja / kuminauha",
    cue: "Vastusta kiertoa ja pidä lantio neutraalina.",
    scope: "global",
  },
  {
    id: "ex_farmers_walk",
    name: "Farmer's walk",
    category: "Koko kroppa",
    equipment: "Käsipainot / farmer-kahvat",
    cue: "Pidä ryhti korkeana ja askel napakkana.",
    scope: "global",
  },
  {
    id: "ex_sled_push",
    name: "Kelkan työntö",
    category: "Koko kroppa",
    equipment: "Kelkka",
    cue: "Pidä vartalo etukenossa ja työnnä tasaisella rytmillä.",
    scope: "global",
  },
  {
    id: "ex_kettlebell_swing",
    name: "Kahvakuulaheilautus",
    category: "Takaketju",
    equipment: "Kahvakuula",
    cue: "Tee liike lantiosta, ei käsillä nostamalla.",
    scope: "global",
  },
  {
    id: "ex_thruster",
    name: "Thruster",
    category: "Koko kroppa",
    equipment: "Levantotanko / käsipainot",
    cue: "Yhdistä kyykky ja pystypunnerrus yhtenä virtana.",
    scope: "global",
  },
];

export const demoState: AppState = {
  users: [
    {
      id: "user_admin_1",
      role: "admin",
      fullName: "Aino Admin",
      email: "admin@rooki.fit",
      status: "active",
      demoPassword: "demo123",
      createdAt: iso(-30),
      updatedAt: iso(-2),
    },
    {
      id: "user_coach_1",
      role: "coach",
      fullName: "Mika Valmentaja",
      email: "coach@rooki.fit",
      status: "active",
      demoPassword: "demo123",
      createdAt: iso(-25),
      updatedAt: iso(-1),
    },
    {
      id: "user_athlete_1",
      role: "athlete",
      fullName: "Sara Treenaaja",
      email: "sara@rooki.fit",
      status: "active",
      demoPassword: "demo123",
      weightKg: 67.8,
      waistCm: 74,
      createdAt: iso(-20),
      updatedAt: iso(-1),
    },
    {
      id: "user_athlete_2",
      role: "athlete",
      fullName: "Elias Kehittyjä",
      email: "elias@rooki.fit",
      status: "active",
      demoPassword: "demo123",
      weightKg: 84.6,
      waistCm: 88,
      createdAt: iso(-18),
      updatedAt: iso(-1),
    },
    {
      id: "user_athlete_3",
      role: "athlete",
      fullName: "Noora Kutsu",
      email: "noora@rooki.fit",
      status: "invited",
      createdAt: iso(-1),
      updatedAt: iso(-1),
    },
  ],
  bodyMeasurements: [
    { id: "measurement_1", userId: "user_athlete_1", weightKg: 69.4, waistCm: 76, measuredAt: iso(-42), createdAt: iso(-42) },
    { id: "measurement_2", userId: "user_athlete_1", weightKg: 68.9, waistCm: 75.5, measuredAt: iso(-35), createdAt: iso(-35) },
    { id: "measurement_3", userId: "user_athlete_1", weightKg: 68.5, waistCm: 75, measuredAt: iso(-28), createdAt: iso(-28) },
    { id: "measurement_4", userId: "user_athlete_1", weightKg: 68.2, waistCm: 74.5, measuredAt: iso(-21), createdAt: iso(-21) },
    { id: "measurement_5", userId: "user_athlete_1", weightKg: 68, waistCm: 74, measuredAt: iso(-14), createdAt: iso(-14) },
    { id: "measurement_6", userId: "user_athlete_1", weightKg: 67.8, waistCm: 74, measuredAt: iso(-7), createdAt: iso(-7) },
    { id: "measurement_7", userId: "user_athlete_2", weightKg: 86.2, waistCm: 90, measuredAt: iso(-35), createdAt: iso(-35) },
    { id: "measurement_8", userId: "user_athlete_2", weightKg: 85.7, waistCm: 89, measuredAt: iso(-21), createdAt: iso(-21) },
    { id: "measurement_9", userId: "user_athlete_2", weightKg: 84.6, waistCm: 88, measuredAt: iso(-7), createdAt: iso(-7) },
  ],
  assignments: [
    {
      id: "assignment_1",
      coachId: "user_coach_1",
      athleteId: "user_athlete_1",
      active: true,
      createdAt: iso(-20),
    },
    {
      id: "assignment_2",
      coachId: "user_coach_1",
      athleteId: "user_athlete_2",
      active: true,
      createdAt: iso(-18),
    },
  ],
  exercises: defaultGlobalExercises,
  templates: [
    {
      id: "template_lower_1",
      coachId: "user_coach_1",
      title: "Voimapäivä A",
      description: "Alavartalon voimapainotteinen treeni viikon alkuun.",
      goal: "Perusvoima + liikeradan laatu",
      splitType: "lower",
      status: "published",
      blocks: [
        {
          id: "block_1",
          title: "Pääsarjat",
          note: "Nosta painoja vain, jos kaikki sarjat tuntuvat hallituilta.",
          exercises: [
            {
              id: "template_ex_1",
              exerciseId: "ex_back_squat",
              instruction: "Pidä 2s pysäytys alhaalla ensimmäisissä kahdessa sarjassa.",
              sets: [
                { id: "set_1", label: "1", targetReps: 5, targetLoad: 70, restSeconds: 120 },
                { id: "set_2", label: "2", targetReps: 5, targetLoad: 70, restSeconds: 120 },
                { id: "set_3", label: "3", targetReps: 5, targetLoad: 72.5, restSeconds: 150 },
              ],
            },
            {
              id: "template_ex_2",
              exerciseId: "ex_romanian_deadlift",
              instruction: "Laske 3 sekuntia alas.",
              sets: [
                { id: "set_4", label: "1", targetReps: 8, targetLoad: 55, restSeconds: 90 },
                { id: "set_5", label: "2", targetReps: 8, targetLoad: 55, restSeconds: 90 },
                { id: "set_6", label: "3", targetReps: 8, targetLoad: 57.5, restSeconds: 90 },
              ],
            },
            {
              id: "template_ex_7",
              exerciseId: "ex_leg_curl",
              instruction: "Purista takareisiä yläasennossa ja laske hallitusti alas.",
              sets: [
                { id: "set_19", label: "1", targetReps: 12, targetLoad: 30, restSeconds: 60 },
                { id: "set_20", label: "2", targetReps: 12, targetLoad: 30, restSeconds: 60 },
                { id: "set_21", label: "3", targetReps: 12, targetLoad: 32.5, restSeconds: 60 },
              ],
            },
            {
              id: "template_ex_8",
              exerciseId: "ex_calf_raise_standing",
              instruction: "Käy täydessä venytyksessä ja pysäytä hetkeksi yläasennossa.",
              sets: [
                { id: "set_22", label: "1", targetReps: 15, targetLoad: 20, restSeconds: 45 },
                { id: "set_23", label: "2", targetReps: 15, targetLoad: 20, restSeconds: 45 },
                { id: "set_24", label: "3", targetReps: 15, targetLoad: 25, restSeconds: 45 },
              ],
            },
          ],
        },
      ],
      createdAt: iso(-14),
      updatedAt: iso(-3),
      createdBy: "user_coach_1",
      updatedBy: "user_coach_1",
    },
    {
      id: "template_upper_1",
      coachId: "user_coach_1",
      title: "Ylävartalo B",
      description: "Työntö-veto -yhdistelmä progressiolla.",
      goal: "Lihaskestävyys ja kontrolli",
      splitType: "upper",
      status: "published",
      blocks: [
        {
          id: "block_2",
          title: "Työosio",
          exercises: [
            {
              id: "template_ex_3",
              exerciseId: "ex_bench_press",
              instruction: "Pidä 1 toisto varaa jokaisessa sarjassa.",
              sets: [
                { id: "set_7", label: "1", targetReps: 8, targetLoad: 45, restSeconds: 90 },
                { id: "set_8", label: "2", targetReps: 8, targetLoad: 45, restSeconds: 90 },
                { id: "set_9", label: "3", targetReps: 8, targetLoad: 47.5, restSeconds: 90 },
              ],
            },
            {
              id: "template_ex_4",
              exerciseId: "ex_row",
              instruction: "Pysäytä yläasennossa sekunti.",
              sets: [
                { id: "set_10", label: "1", targetReps: 10, targetLoad: 18, restSeconds: 60 },
                { id: "set_11", label: "2", targetReps: 10, targetLoad: 18, restSeconds: 60 },
                { id: "set_12", label: "3", targetReps: 10, targetLoad: 20, restSeconds: 60 },
              ],
            },
            {
              id: "template_ex_9",
              exerciseId: "ex_overhead_press",
              instruction: "Pidä keskivartalo tiukkana ja työnnä suoraan ylös.",
              sets: [
                { id: "set_25", label: "1", targetReps: 8, targetLoad: 25, restSeconds: 75 },
                { id: "set_26", label: "2", targetReps: 8, targetLoad: 25, restSeconds: 75 },
                { id: "set_27", label: "3", targetReps: 8, targetLoad: 27.5, restSeconds: 75 },
              ],
            },
            {
              id: "template_ex_10",
              exerciseId: "ex_lat_pulldown",
              instruction: "Vedä kyynärpäät alas ja taakse ilman nykäisyä.",
              sets: [
                { id: "set_28", label: "1", targetReps: 10, targetLoad: 40, restSeconds: 60 },
                { id: "set_29", label: "2", targetReps: 10, targetLoad: 40, restSeconds: 60 },
                { id: "set_30", label: "3", targetReps: 10, targetLoad: 45, restSeconds: 60 },
              ],
            },
          ],
        },
      ],
      createdAt: iso(-12),
      updatedAt: iso(-2),
      createdBy: "user_coach_1",
      updatedBy: "user_coach_1",
    },
    {
      id: "template_full_1",
      coachId: "user_coach_1",
      title: "Koko kroppa C",
      description: "Koko kehon kontrolli- ja tukivoimapäivä viikon loppuun.",
      goal: "Tasapaino + liikehallinta + kokonaiskuorma",
      splitType: "full_body",
      status: "published",
      blocks: [
        {
          id: "block_3",
          title: "Full body flow",
          exercises: [
            {
              id: "template_ex_5",
              exerciseId: "ex_split_squat",
              instruction: "Pidä lantio suorassa ja kontrolloi jokainen toisto.",
              sets: [
                { id: "set_13", label: "1", targetReps: 10, targetLoad: 14, restSeconds: 75 },
                { id: "set_14", label: "2", targetReps: 10, targetLoad: 14, restSeconds: 75 },
                { id: "set_15", label: "3", targetReps: 10, targetLoad: 16, restSeconds: 75 },
              ],
            },
            {
              id: "template_ex_6",
              exerciseId: "ex_plank",
              instruction: "Pidä keskivartalo aktiivisena koko sarjan ajan.",
              sets: [
                { id: "set_16", label: "1", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
                { id: "set_17", label: "2", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
                { id: "set_18", label: "3", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
              ],
            },
            {
              id: "template_ex_11",
              exerciseId: "ex_incline_db_press",
              instruction: "Pidä lavat tuettuina penkkiin ja työnnä tasaisesti ylös.",
              sets: [
                { id: "set_31", label: "1", targetReps: 10, targetLoad: 16, restSeconds: 75 },
                { id: "set_32", label: "2", targetReps: 10, targetLoad: 16, restSeconds: 75 },
                { id: "set_33", label: "3", targetReps: 10, targetLoad: 18, restSeconds: 75 },
              ],
            },
            {
              id: "template_ex_12",
              exerciseId: "ex_seated_cable_row",
              instruction: "Vedä kyynärpäät taakse ja pysäytä hetkeksi loppuasentoon.",
              sets: [
                { id: "set_34", label: "1", targetReps: 12, targetLoad: 35, restSeconds: 60 },
                { id: "set_35", label: "2", targetReps: 12, targetLoad: 35, restSeconds: 60 },
                { id: "set_36", label: "3", targetReps: 12, targetLoad: 40, restSeconds: 60 },
              ],
            },
          ],
        },
      ],
      createdAt: iso(-10),
      updatedAt: iso(-2),
      createdBy: "user_coach_1",
      updatedBy: "user_coach_1",
    },
  ],
  plans: [
    {
      id: "plan_1",
      coachId: "user_coach_1",
      athleteId: "user_athlete_1",
      title: "Sara 4 viikon voimaohjelma",
      workouts: [
        {
          id: "program_workout_upper_1",
          name: "Ylävartalo B",
          splitType: "upper",
          defaultRestSeconds: 90,
          exercises: [
            {
              id: "program_ex_1",
              exerciseId: "ex_bench_press",
              exerciseName: "Penkkipunnerrus",
              muscleGroup: "chest",
              instruction: "Pidä 1 toisto varaa jokaisessa sarjassa.",
              sets: [
                { id: "program_set_1", label: "1", targetReps: 8, targetLoad: 45, restSeconds: 90 },
                { id: "program_set_2", label: "2", targetReps: 8, targetLoad: 45, restSeconds: 90 },
                { id: "program_set_3", label: "3", targetReps: 8, targetLoad: 47.5, restSeconds: 90 },
              ],
            },
            {
              id: "program_ex_2",
              exerciseId: "ex_row",
              exerciseName: "Kulmasoutu",
              muscleGroup: "back",
              instruction: "Pysäytä yläasennossa sekunti.",
              sets: [
                { id: "program_set_4", label: "1", targetReps: 10, targetLoad: 18, restSeconds: 60 },
                { id: "program_set_5", label: "2", targetReps: 10, targetLoad: 18, restSeconds: 60 },
                { id: "program_set_6", label: "3", targetReps: 10, targetLoad: 20, restSeconds: 60 },
              ],
            },
            {
              id: "program_ex_7",
              exerciseId: "ex_overhead_press",
              exerciseName: "Pystypunnerrus tangolla",
              muscleGroup: "shoulders",
              instruction: "Pidä keskivartalo tiukkana ja työnnä suoraan ylös.",
              sets: [
                { id: "program_set_19", label: "1", targetReps: 8, targetLoad: 25, restSeconds: 75 },
                { id: "program_set_20", label: "2", targetReps: 8, targetLoad: 25, restSeconds: 75 },
                { id: "program_set_21", label: "3", targetReps: 8, targetLoad: 27.5, restSeconds: 75 },
              ],
            },
            {
              id: "program_ex_8",
              exerciseId: "ex_lat_pulldown",
              exerciseName: "Ylätalja",
              muscleGroup: "back",
              instruction: "Vedä kyynärpäät alas ja taakse ilman nykäisyä.",
              sets: [
                { id: "program_set_22", label: "1", targetReps: 10, targetLoad: 40, restSeconds: 60 },
                { id: "program_set_23", label: "2", targetReps: 10, targetLoad: 40, restSeconds: 60 },
                { id: "program_set_24", label: "3", targetReps: 10, targetLoad: 45, restSeconds: 60 },
              ],
            },
          ],
        },
        {
          id: "program_workout_lower_1",
          name: "Voimapäivä A",
          splitType: "lower",
          defaultRestSeconds: 120,
          exercises: [
            {
              id: "program_ex_3",
              exerciseId: "ex_back_squat",
              exerciseName: "Takakyykky",
              muscleGroup: "legs",
              instruction: "Pidä 2s pysäytys alhaalla ensimmäisissä kahdessa sarjassa.",
              sets: [
                { id: "program_set_7", label: "1", targetReps: 5, targetLoad: 70, restSeconds: 120 },
                { id: "program_set_8", label: "2", targetReps: 5, targetLoad: 70, restSeconds: 120 },
                { id: "program_set_9", label: "3", targetReps: 5, targetLoad: 72.5, restSeconds: 150 },
              ],
            },
            {
              id: "program_ex_4",
              exerciseId: "ex_romanian_deadlift",
              exerciseName: "Romanialainen maastaveto",
              muscleGroup: "legs",
              instruction: "Laske 3 sekuntia alas.",
              sets: [
                { id: "program_set_10", label: "1", targetReps: 8, targetLoad: 55, restSeconds: 90 },
                { id: "program_set_11", label: "2", targetReps: 8, targetLoad: 55, restSeconds: 90 },
                { id: "program_set_12", label: "3", targetReps: 8, targetLoad: 57.5, restSeconds: 90 },
              ],
            },
            {
              id: "program_ex_9",
              exerciseId: "ex_leg_curl",
              exerciseName: "Takareisikoukistus",
              muscleGroup: "legs",
              instruction: "Purista takareisiä yläasennossa ja laske hallitusti alas.",
              sets: [
                { id: "program_set_25", label: "1", targetReps: 12, targetLoad: 30, restSeconds: 60 },
                { id: "program_set_26", label: "2", targetReps: 12, targetLoad: 30, restSeconds: 60 },
                { id: "program_set_27", label: "3", targetReps: 12, targetLoad: 32.5, restSeconds: 60 },
              ],
            },
            {
              id: "program_ex_10",
              exerciseId: "ex_calf_raise_standing",
              exerciseName: "Pohjenousu seisten",
              muscleGroup: "legs",
              instruction: "Käy täydessä venytyksessä ja pysäytä hetkeksi yläasennossa.",
              sets: [
                { id: "program_set_28", label: "1", targetReps: 15, targetLoad: 20, restSeconds: 45 },
                { id: "program_set_29", label: "2", targetReps: 15, targetLoad: 20, restSeconds: 45 },
                { id: "program_set_30", label: "3", targetReps: 15, targetLoad: 25, restSeconds: 45 },
              ],
            },
          ],
        },
        {
          id: "program_workout_full_1",
          name: "Koko kroppa C",
          splitType: "full_body",
          defaultRestSeconds: 75,
          exercises: [
            {
              id: "program_ex_5",
              exerciseId: "ex_split_squat",
              exerciseName: "Bulgarialainen askelkyykky",
              muscleGroup: "legs",
              instruction: "Pidä lantio suorassa ja kontrolloi jokainen toisto.",
              sets: [
                { id: "program_set_13", label: "1", targetReps: 10, targetLoad: 14, restSeconds: 75 },
                { id: "program_set_14", label: "2", targetReps: 10, targetLoad: 14, restSeconds: 75 },
                { id: "program_set_15", label: "3", targetReps: 10, targetLoad: 16, restSeconds: 75 },
              ],
            },
            {
              id: "program_ex_6",
              exerciseId: "ex_plank",
              exerciseName: "Lankku",
              muscleGroup: "abs",
              instruction: "Pidä keskivartalo aktiivisena koko sarjan ajan.",
              sets: [
                { id: "program_set_16", label: "1", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
                { id: "program_set_17", label: "2", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
                { id: "program_set_18", label: "3", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
              ],
            },
            {
              id: "program_ex_11",
              exerciseId: "ex_incline_db_press",
              exerciseName: "Vinopenkki käsipainoilla",
              muscleGroup: "chest",
              instruction: "Pidä lavat tuettuina penkkiin ja työnnä tasaisesti ylös.",
              sets: [
                { id: "program_set_31", label: "1", targetReps: 10, targetLoad: 16, restSeconds: 75 },
                { id: "program_set_32", label: "2", targetReps: 10, targetLoad: 16, restSeconds: 75 },
                { id: "program_set_33", label: "3", targetReps: 10, targetLoad: 18, restSeconds: 75 },
              ],
            },
            {
              id: "program_ex_12",
              exerciseId: "ex_seated_cable_row",
              exerciseName: "Istuva soutu taljassa",
              muscleGroup: "back",
              instruction: "Vedä kyynärpäät taakse ja pysäytä hetkeksi loppuasentoon.",
              sets: [
                { id: "program_set_34", label: "1", targetReps: 12, targetLoad: 35, restSeconds: 60 },
                { id: "program_set_35", label: "2", targetReps: 12, targetLoad: 35, restSeconds: 60 },
                { id: "program_set_36", label: "3", targetReps: 12, targetLoad: 40, restSeconds: 60 },
              ],
            },
          ],
        },
      ],
      startDate: iso(-7),
      weekCount: 4,
      createdAt: iso(-7),
      updatedAt: iso(-2),
    },
  ],
  scheduledWorkouts: [
    {
      id: "scheduled_5",
      trainingPlanId: "plan_1",
      templateId: "template_upper_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      title: "Ylävartalo B",
      scheduledDate: iso(-8),
      status: "completed",
      createdAt: iso(-10),
      updatedAt: iso(-8),
      completedAt: iso(-8),
    },
    {
      id: "scheduled_1",
      trainingPlanId: "plan_1",
      templateId: "template_lower_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      title: "Voimapäivä A",
      scheduledDate: iso(-1),
      status: "completed",
      createdAt: iso(-4),
      updatedAt: iso(-1),
      completedAt: iso(-1),
    },
    {
      id: "scheduled_2",
      trainingPlanId: "plan_1",
      templateId: "template_upper_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      title: "Ylävartalo B",
      scheduledDate: iso(0),
      status: "in_progress",
      createdAt: iso(-3),
      updatedAt: iso(0),
    },
    {
      id: "scheduled_3",
      templateId: "template_lower_1",
      athleteId: "user_athlete_2",
      coachId: "user_coach_1",
      title: "Voimapäivä A",
      scheduledDate: iso(1),
      status: "cancelled",
      createdAt: iso(-2),
      updatedAt: iso(-2),
    },
    {
      id: "scheduled_4",
      trainingPlanId: "plan_1",
      templateId: "template_full_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      title: "Koko kroppa C",
      scheduledDate: iso(2),
      status: "cancelled",
      createdAt: iso(-2),
      updatedAt: iso(-2),
    },
  ],
  sessions: [
    {
      id: "session_3",
      scheduledWorkoutId: "scheduled_5",
      athleteId: "user_athlete_1",
      startedAt: iso(-8),
      completedAt: iso(-8),
      updatedAt: iso(-8),
      energyLevel: 4,
      setLogs: [
        {
          id: "log_9",
          scheduledWorkoutId: "scheduled_5",
          templateExerciseId: "template_ex_3",
          setId: "set_7",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "1",
          targetReps: 8,
          targetLoad: 45,
          actualReps: 8,
          actualLoad: 45,
          rpe: 7,
          done: true,
        },
        {
          id: "log_10",
          scheduledWorkoutId: "scheduled_5",
          templateExerciseId: "template_ex_3",
          setId: "set_8",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "2",
          targetReps: 8,
          targetLoad: 45,
          actualReps: 8,
          actualLoad: 45,
          rpe: 8,
          done: true,
        },
        {
          id: "log_11",
          scheduledWorkoutId: "scheduled_5",
          templateExerciseId: "template_ex_4",
          setId: "set_10",
          exerciseId: "ex_row",
          exerciseName: "Kulmasoutu",
          setLabel: "1",
          targetReps: 10,
          targetLoad: 18,
          actualReps: 10,
          actualLoad: 18,
          rpe: 7,
          done: true,
        },
      ],
    },
    {
      id: "session_1",
      scheduledWorkoutId: "scheduled_1",
      athleteId: "user_athlete_1",
      startedAt: iso(-1),
      completedAt: iso(-1),
      updatedAt: iso(-1),
      energyLevel: 4,
      setLogs: [
        {
          id: "log_1",
          scheduledWorkoutId: "scheduled_1",
          templateExerciseId: "template_ex_1",
          setId: "set_1",
          exerciseId: "ex_back_squat",
          exerciseName: "Takakyykky",
          setLabel: "1",
          targetReps: 5,
          targetLoad: 70,
          actualReps: 5,
          actualLoad: 70,
          rpe: 7,
          done: true,
        },
        {
          id: "log_2",
          scheduledWorkoutId: "scheduled_1",
          templateExerciseId: "template_ex_1",
          setId: "set_2",
          exerciseId: "ex_back_squat",
          exerciseName: "Takakyykky",
          setLabel: "2",
          targetReps: 5,
          targetLoad: 70,
          actualReps: 5,
          actualLoad: 70,
          rpe: 8,
          done: true,
        },
      ],
    },
    {
      id: "session_2",
      scheduledWorkoutId: "scheduled_2",
      athleteId: "user_athlete_1",
      startedAt: iso(0),
      updatedAt: iso(0),
      energyLevel: 3,
      setLogs: [
        {
          id: "log_3",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "template_ex_3",
          setId: "set_7",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "1",
          targetReps: 8,
          targetLoad: 45,
          actualReps: 8,
          actualLoad: 45,
          rpe: 7,
          done: true,
        },
        {
          id: "log_4",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "template_ex_3",
          setId: "set_8",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "2",
          targetReps: 8,
          targetLoad: 45,
          done: false,
        },
        {
          id: "log_5",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "template_ex_3",
          setId: "set_9",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "3",
          targetReps: 8,
          targetLoad: 47.5,
          done: false,
        },
        {
          id: "log_6",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "template_ex_4",
          setId: "set_10",
          exerciseId: "ex_row",
          exerciseName: "Kulmasoutu",
          setLabel: "1",
          targetReps: 10,
          targetLoad: 18,
          done: false,
        },
        {
          id: "log_7",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "template_ex_4",
          setId: "set_11",
          exerciseId: "ex_row",
          exerciseName: "Kulmasoutu",
          setLabel: "2",
          targetReps: 10,
          targetLoad: 18,
          done: false,
        },
        {
          id: "log_8",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "template_ex_4",
          setId: "set_12",
          exerciseId: "ex_row",
          exerciseName: "Kulmasoutu",
          setLabel: "3",
          targetReps: 10,
          targetLoad: 20,
          done: false,
        },
      ],
    },
  ],
  notes: [
    {
      id: "note_1",
      sessionId: "session_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      body: "Takakyykky tuntui vakaalta. Voidaan nostaa 2,5 kg ensi viikolla.",
      createdAt: iso(-1),
      updatedAt: iso(-1),
    },
  ],
  conversationEntries: [
    {
      id: "conversation_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      authorUserId: "user_athlete_1",
      authorRole: "athlete",
      type: "comment",
      body: "Kyykyn viimeinen sarja oli jo aika raskas, mutta tekniikka pysyi kasassa.",
      contextType: "workout",
      contextId: "scheduled_1",
      contextLabel: "Alakroppa 1",
      createdAt: iso(-1),
      readByUserIds: ["user_athlete_1"],
    },
    {
      id: "conversation_2",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      authorUserId: "user_coach_1",
      authorRole: "coach",
      type: "comment",
      body: "Hyvä huomio. Pidetään ensi viikolla sama kuorma ja haetaan puhtaampi loppu.",
      contextType: "workout",
      contextId: "scheduled_1",
      contextLabel: "Alakroppa 1",
      createdAt: iso(0),
      readByUserIds: ["user_coach_1"],
    },
  ],
  invites: [
    {
      id: "invite_1",
      token: "join-noora-demo",
      email: "noora@rooki.fit",
      role: "athlete",
      invitedBy: "user_coach_1",
      coachId: "user_coach_1",
      status: "pending",
      createdAt: iso(-1),
      expiresAt: iso(6),
    },
  ],
  passwordResetRequests: [],
};
