import type { AppState } from "@/lib/types";

const today = new Date();
const iso = (offsetDays: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + offsetDays);
  date.setHours(8, 0, 0, 0);
  return date.toISOString();
};

export const defaultGlobalExercises: AppState["exercises"] = [
  {
    id: "ex_back_squat",
    name: "Takakyykky",
    category: "Alavartalo",
    equipment: "Levantotanko",
    cue: "Asetu tukevasti tangon alle, jännitä keskivartalo ja pidä rintakehä avoinna. Istuudu hallitusti alas koko jalkapohjalle ja aja ylös painamalla lattiaa pois alta.",
    scope: "global",
  },
  {
    id: "ex_front_squat",
    name: "Etukyykky",
    category: "Alavartalo",
    equipment: "Levantotanko",
    cue: "Pidä kyynärpäät korkealla ja tanko tukevasti etuharteilla. Laskeudu suoraan alas hallitusti ja nouse ylös säilyttäen pysty vartalo ja keskivartalon tuki.",
    scope: "global",
  },
  {
    id: "ex_goblet_squat",
    name: "Goblet-kyykky",
    category: "Alavartalo",
    equipment: "Käsipaino / Kahvakuula",
    cue: "Pidä paino lähellä rintaa ja rintakehä avoinna koko liikkeen ajan. Laskeudu alas kantapäät maassa ja työnnä polvia varpaiden suuntaan.",
    scope: "global",
  },
  {
    id: "ex_leg_press",
    name: "Jalkaprässi",
    category: "Alavartalo",
    equipment: "Jalkaprässi",
    cue: "Aseta jalat tasaisesti levylle ja pidä alaselkä kiinni tuessa. Laskeudu hallitusti sopivaan syvyyteen ja työnnä levy ylös ilman että polvet lukittuvat voimalla.",
    scope: "global",
  },
  {
    id: "ex_hack_squat",
    name: "Hack-kyykky",
    category: "Alavartalo",
    equipment: "Hack-laite",
    cue: "Pidä selkä tukevasti alustaa vasten ja keskivartalo jännittyneenä. Laskeudu hallitusti alas ja työnnä ylös koko jalkapohjan kautta.",
    scope: "global",
  },
  {
    id: "ex_split_squat",
    name: "Bulgarialainen askelkyykky",
    category: "Alavartalo",
    equipment: "Käsipainot",
    cue: "Aseta etujalka tukevasti maahan ja pidä paino pääosin etujalalla. Laskeudu suoraan alas hallitusti ja työnnä ylös ilman että takajalka tekee liikaa työtä.",
    scope: "global",
  },
  {
    id: "ex_walking_lunge",
    name: "Kävelyaskelkyykky",
    category: "Alavartalo",
    equipment: "Käsipainot",
    cue: "Pidä vartalo pystyssä ja askel riittävän pitkänä, jotta etupolvi pysyy hallinnassa. Työnnä jokainen askel ylös etujalan kautta ja säilytä tasainen rytmi.",
    scope: "global",
  },
  {
    id: "ex_step_up",
    name: "Step-up",
    category: "Alavartalo",
    equipment: "Boksi + käsipainot",
    cue: "Aseta koko etujalka korokkeelle ja pidä lantio suorassa. Työnnä itsesi ylös etujalan kautta ilman ponnistusta takajalalla.",
    scope: "global",
  },
  {
    id: "ex_romanian_deadlift",
    name: "Romanialainen maastaveto",
    category: "Takaketju",
    equipment: "Levantotanko",
    cue: "Pidä tanko lähellä reisiä ja selkä neutraalina koko liikkeen ajan. Vie lantiota taakse hallitusti ja nouse ylös puristamalla pakarat.",
    scope: "global",
  },
  {
    id: "ex_deadlift",
    name: "Maastaveto",
    category: "Takaketju",
    equipment: "Levantotanko",
    cue: "Asetu tangon päälle siten, että tanko on lähellä sääriä ja selkä neutraali. Jännitä keskivartalo, työnnä lattiaa pois jaloilla ja vedä tanko ylös vartaloa pitkin.",
    scope: "global",
  },
  {
    id: "ex_sumo_deadlift",
    name: "Sumomaastaveto",
    category: "Takaketju",
    equipment: "Levantotanko",
    cue: "Aseta jalat leveälle ja polvet varpaiden suuntaan. Pidä rintakehä korkealla, työnnä lattiaa sivuille ja vedä tanko ylös lähellä vartaloa.",
    scope: "global",
  },
  {
    id: "ex_good_morning",
    name: "Good morning",
    category: "Takaketju",
    equipment: "Levantotanko",
    cue: "Pidä polvissa kevyt koukku ja tanko vakaasti yläselällä. Työnnä lantiota taakse ja pidä selkä neutraalina koko alas- ja ylösliikkeen ajan.",
    scope: "global",
  },
  {
    id: "ex_hip_thrust",
    name: "Hip thrust",
    category: "Pakarat",
    equipment: "Penkki + tanko",
    cue: "Aseta yläselkä penkkiä vasten ja pidä leuka kevyesti alhaalla. Työnnä lantio ylös puristaen pakaroita ja vältä alaselän yliojennusta.",
    scope: "global",
  },
  {
    id: "ex_glute_bridge",
    name: "Glute bridge",
    category: "Pakarat",
    equipment: "Kehonpaino / tanko",
    cue: "Pidä jalkapohjat tukevasti maassa ja kylkiluut alhaalla. Nosta lantio linjaan hallitusti ja purista pakarat yläasennossa.",
    scope: "global",
  },
  {
    id: "ex_leg_curl",
    name: "Takareisikoukistus",
    category: "Alavartalo",
    equipment: "Leg curl -laite",
    cue: "Pidä lantio tuettuna alustaa vasten ja liike rauhallisena. Vedä kantapäät kohti pakaroita hallitusti ja laske takaisin ilman heilautusta.",
    scope: "global",
  },
  {
    id: "ex_leg_extension",
    name: "Jalanojennus",
    category: "Alavartalo",
    equipment: "Leg extension -laite",
    cue: "Säädä polvi nivelakselin kohdalle ja pidä reidet tukevasti penkissä. Ojenna polvet hallitusti, pysäytä hetkeksi yläasentoon ja laske rauhassa alas.",
    scope: "global",
  },
  {
    id: "ex_calf_raise_standing",
    name: "Pohjenousu seisten",
    category: "Alavartalo",
    equipment: "Pohjelaite / käsipainot",
    cue: "Anna kantapäiden laskea alas täyteen venytykseen ja pidä paino päkiöillä. Nouse hallitusti ylös varpaille asti ja pysäytä hetkeksi yläasentoon.",
    scope: "global",
  },
  {
    id: "ex_calf_raise_seated",
    name: "Pohjenousu istuen",
    category: "Alavartalo",
    equipment: "Istuva pohjelaite",
    cue: "Pidä reidet tukevasti alustaa vasten ja hae pohkeeseen täysi venytys ala-asennossa. Nouse hallitusti päkiöille ja jarruta lasku takaisin alas.",
    scope: "global",
  },
  {
    id: "ex_hip_abduction_machine",
    name: "Lonkan loitonnus laitteessa",
    category: "Pakarat",
    equipment: "Abductor-laite",
    cue: "Pidä lantio tukevasti alustaa vasten ja keskivartalo vakaana. Avaa jalat ulos hallitusti ja palauta liike takaisin ilman nykäisyä.",
    scope: "global",
  },
  {
    id: "ex_hip_adduction_machine",
    name: "Lonkan lähennys laitteessa",
    category: "Alavartalo",
    equipment: "Adductor-laite",
    cue: "Pidä lantio paikallaan ja aloita liike hallitusti sisäreisillä. Purista jalat yhteen loppuasentoon ja palauta rauhassa alkuun.",
    scope: "global",
  },
  {
    id: "ex_bench_press",
    name: "Penkkipunnerrus",
    category: "Rinta",
    equipment: "Penkki + tanko",
    cue: "Asetu penkille selinmakuulle jalat tukevasti maahan. Vedä lapaluut yhteen ja alas sekä pidä alaselässä kevyt kaari.\n\nOta tangosta hieman hartioita leveämpi ote ja pidä ranteet suorina. Aloita tanko hartioiden yläpuolelta.\n\nLaske tanko hallitusti rinnan alaosaan kyynärpäät noin 30-60 asteen kulmassa vartalosta.\n\nPunnerra tanko takaisin ylös loivassa kaaressa suorille käsille. Pidä keho jännittyneenä ja vältä pomputusta.\n\nHengitä sisään alas laskiessa ja ulos ylös työntäessä.",
    scope: "global",
  },
  {
    id: "ex_incline_bench_press",
    name: "Vinopenkki tangolla",
    category: "Rinta",
    equipment: "Vinopenkki + tanko",
    cue: "Vedä lapaluut yhteen ja pidä jalat tukevasti maassa. Laske tanko hallitusti ylä- tai keskirinnan suuntaan ja punnersa ylös ilman että kyynärpäät leviävät liikaa.",
    scope: "global",
  },
  {
    id: "ex_decline_bench_press",
    name: "Alavinopenkki tangolla",
    category: "Rinta",
    equipment: "Alavinopenkki + tanko",
    cue: "Pidä lapatuet tiukkana ja ranne-tankolinja vakaana. Laske tanko hallitusti alarinnan suuntaan ja työnnä takaisin ylös tasaisella voimalla.",
    scope: "global",
  },
  {
    id: "ex_db_bench_press",
    name: "Käsipainopenkki",
    category: "Rinta",
    equipment: "Penkki + käsipainot",
    cue: "Vedä lapaluut yhteen ja pidä käsipainot hallinnassa koko liikeradan ajan. Laske kyynärpäät hallitusti alas ja työnnä painot ylös loivassa kaaressa.",
    scope: "global",
  },
  {
    id: "ex_incline_db_press",
    name: "Vinopenkki käsipainoilla",
    category: "Rinta",
    equipment: "Vinopenkki + käsipainot",
    cue: "Pidä lapatuet aktiivisina ja olkapäät alhaalla koko sarjan ajan. Laske käsipainot hallitusti alas ja työnnä takaisin ylös vakaalla liikeradalla.",
    scope: "global",
  },
  {
    id: "ex_chest_fly_db",
    name: "Rintafly käsipainoilla",
    category: "Rinta",
    equipment: "Penkki + käsipainot",
    cue: "Pidä kyynärpäissä kevyt koukku ja rintakehä avoinna. Avaa kädet hallitusti venytykseen ja tuo painot takaisin yhteen ilman että hartiat nousevat.",
    scope: "global",
  },
  {
    id: "ex_cable_fly",
    name: "Taljafly",
    category: "Rinta",
    equipment: "Talja",
    cue: "Asetu vakaaseen asentoon ja pidä rintakehä korkealla. Vie kädet yhteen kaarella rintaa puristaen ja palauta hallitusti venytykseen.",
    scope: "global",
  },
  {
    id: "ex_pec_deck",
    name: "Pec deck",
    category: "Rinta",
    equipment: "Pec deck -laite",
    cue: "Pidä hartiat alhaalla ja kyynärpäät pehmeinä. Purista kädet yhteen rinnan avulla ja jarruta palautus takaisin venytykseen.",
    scope: "global",
  },
  {
    id: "ex_push_up",
    name: "Punnerrus",
    category: "Rinta",
    equipment: "Kehonpaino",
    cue: "Pidä vartalo suorassa linjassa päästä kantapäihin ja keskivartalo tiukkana. Laskeudu hallitusti alas ja työnnä ylös ilman että lantio roikkuu.",
    scope: "global",
  },
  {
    id: "ex_dips",
    name: "Dippi",
    category: "Rinta / ojentajat",
    equipment: "Dippiteline",
    cue: "Pidä hartiat alhaalla ja rintakehä avoinna. Laskeudu hallitusti kyynärpäät takaviistoon ja työnnä itsesi ylös ilman heilautusta.",
    scope: "global",
  },
  {
    id: "ex_overhead_press",
    name: "Pystypunnerrus tangolla",
    category: "Hartiat",
    equipment: "Levantotanko",
    cue: "Purista pakarat ja keskivartalo tiukaksi ennen nostoa. Työnnä tanko suoraan ylös pään yli ja vie pää läpi yläasennossa.",
    scope: "global",
  },
  {
    id: "ex_seated_db_press",
    name: "Istuva pystypunnerrus käsipainoilla",
    category: "Hartiat",
    equipment: "Penkki + käsipainot",
    cue: "Asetu tukevasti penkkiin ja pidä kyynärpäät ranteiden alla. Punnerra painot suoraan ylös hallitusti ja laske takaisin ilman että hartiat kohoavat.",
    scope: "global",
  },
  {
    id: "ex_arnold_press",
    name: "Arnold press",
    category: "Hartiat",
    equipment: "Käsipainot",
    cue: "Aloita kämmenet itseä kohti kyynärpäät edessä. Kierrä kädet punnerruksen aikana ylös ja palauta liike hallitusti takaisin alkuasentoon.",
    scope: "global",
  },
  {
    id: "ex_lateral_raise",
    name: "Vipunosto sivulle",
    category: "Hartiat",
    equipment: "Käsipainot / talja",
    cue: "Pidä kyynärpäissä kevyt kulma ja nosta kädet sivuille hartialinjalle asti. Vältä vauhdinottoa ja pidä niska rentona.",
    scope: "global",
  },
  {
    id: "ex_front_raise",
    name: "Vipunosto eteen",
    category: "Hartiat",
    equipment: "Käsipainot / levypaino",
    cue: "Pidä keskivartalo vakaana ja nosta paino hallitusti eteen hartialinjalle. Laske takaisin alas ilman että nojaat taakse.",
    scope: "global",
  },
  {
    id: "ex_rear_delt_fly",
    name: "Takaolkapääfly",
    category: "Hartiat",
    equipment: "Käsipainot / pec deck",
    cue: "Nojaa eteenpäin vakaasti ja pidä niska neutraalina. Avaa kädet sivuille takaolkapäillä ja jarruta palautus alas.",
    scope: "global",
  },
  {
    id: "ex_upright_row",
    name: "Pystysoutu",
    category: "Hartiat",
    equipment: "Tanko / käsipainot",
    cue: "Vedä paino ylös vartalon läheltä kyynärpäät johtavana. Pidä liike hallittuna ja lopeta ennen kuin hartiat nousevat korviin.",
    scope: "global",
  },
  {
    id: "ex_row",
    name: "Kulmasoutu",
    category: "Selkä",
    equipment: "Käsipainot",
    cue: "Pidä tuki vakaana ja selkä neutraalina. Vedä kyynärpää kohti lantiota ja purista lapaa yhteen yläasennossa.",
    scope: "global",
  },
  {
    id: "ex_barbell_row",
    name: "Kulmasoutu tangolla",
    category: "Selkä",
    equipment: "Levantotanko",
    cue: "Hae vahva etunoja ja pidä keskivartalo tiukkana. Vedä tanko alavatsalle ilman että ylävartalo nousee.",
    scope: "global",
  },
  {
    id: "ex_chest_supported_row",
    name: "Rintasoutu penkiltä",
    category: "Selkä",
    equipment: "Vinopenkki + käsipainot",
    cue: "Pidä rintakehä tukevasti penkkiä vasten koko sarjan ajan. Vedä kyynärpäät taakse ja purista lapoja yhteen yläasennossa.",
    scope: "global",
  },
  {
    id: "ex_seated_cable_row",
    name: "Istuva soutu taljassa",
    category: "Selkä",
    equipment: "Talja",
    cue: "Istahda vakaasti ja pidä rintakehä korkealla. Vedä kahva kohti napaa, pysäytä hetkeksi ja palauta rauhallisesti.",
    scope: "global",
  },
  {
    id: "ex_low_cable_row",
    name: "Alatalja",
    category: "Selkä",
    equipment: "Alatalja",
    cue: "Pidä rintakehä ylhäällä ja keskivartalo vakaana koko vedon ajan. Vedä kyynärpäät taakse ja jarruta palautus hallitusti alkuun.",
    scope: "global",
  },
  {
    id: "ex_lat_pulldown",
    name: "Ylätalja",
    category: "Selkä",
    equipment: "Ylätalja",
    cue: "Pidä rintakehä ylhäällä ja aloita veto lapojen aktivoinnilla. Vedä tanko ylärinnan suuntaan kyynärpäät alas ja taakse ilman nykäisyä.",
    scope: "global",
  },
  {
    id: "ex_pull_up",
    name: "Leuanveto myötäotteella",
    category: "Selkä",
    equipment: "Leuanvetotanko",
    cue: "Aloita roikunnasta aktivoimalla lavat ja jännittämällä keskivartalo. Vedä itsesi ylös rinta kohti tankoa ilman heiluriliikettä.",
    scope: "global",
  },
  {
    id: "ex_chin_up",
    name: "Leuanveto vastaotteella",
    category: "Selkä / hauis",
    equipment: "Leuanvetotanko",
    cue: "Pidä keskivartalo tiukkana ja aloita veto lapojen kautta. Vedä leuka tangon yli hallitusti ja laskeudu täyteen roikuntaan kontrolloidusti.",
    scope: "global",
  },
  {
    id: "ex_single_arm_cable_row",
    name: "Yhden käden soutu taljassa",
    category: "Selkä",
    equipment: "Talja",
    cue: "Pidä lantio ja rintakehä vakaana koko vedon ajan. Vedä kyynärpää taakse kyljen suuntaan ja jarruta palautus.",
    scope: "global",
  },
  {
    id: "ex_face_pull",
    name: "Face pull",
    category: "Yläselkä",
    equipment: "Talja + köysi",
    cue: "Vedä köysi kasvojen korkeudelle kyynärpäät leveinä. Kierrä peukalot taakse ja pidä yläselkä aktiivisena.",
    scope: "global",
  },
  {
    id: "ex_shrug",
    name: "Hartiannosto",
    category: "Yläselkä",
    equipment: "Käsipainot / tanko",
    cue: "Pidä kädet suorina ja nosta hartiat suoraan ylöspäin. Pysäytä hetkeksi yläasennossa ja laske hitaasti alas.",
    scope: "global",
  },
  {
    id: "ex_straight_arm_pulldown",
    name: "Suorin käsin ylätaljaveto",
    category: "Selkä",
    equipment: "Talja",
    cue: "Pidä rintakehä avoinna ja kyynärpäissä kevyt kulma. Vedä kädet alas lantiolle latseilla ilman että nojaat liikaa.",
    scope: "global",
  },
  {
    id: "ex_close_grip_bench_press",
    name: "Kapea penkkipunnerrus",
    category: "Ojentajat",
    equipment: "Penkki + tanko",
    cue: "Pidä ote hartioita kapeampana ja kyynärpäät lähellä vartaloa. Laske tanko hallitusti alarinnan suuntaan ja punnersa ylös ojentajilla.",
    scope: "global",
  },
  {
    id: "ex_tricep_pushdown",
    name: "Ojentajapunnerrus taljassa",
    category: "Ojentajat",
    equipment: "Talja",
    cue: "Pidä kyynärpäät kiinni kyljissä ja hartiat alhaalla. Ojenna kyynärpäät loppuun asti ja palauta hallitusti takaisin ylös.",
    scope: "global",
  },
  {
    id: "ex_overhead_tricep_extension",
    name: "Ojentaja pään yli",
    category: "Ojentajat",
    equipment: "Köysitalja / käsipaino",
    cue: "Pidä yläkädet paikallaan ja kyynärpäät osoittamassa eteen. Laske paino venytykseen pään taakse ja ojenna hallitusti ylös.",
    scope: "global",
  },
  {
    id: "ex_skullcrusher",
    name: "Ranskalainen punnerrus",
    category: "Ojentajat",
    equipment: "EZ-tanko / käsipainot",
    cue: "Pidä olkavarret mahdollisimman paikallaan ja kyynärpäät osoittamassa ylös. Laske paino hallitusti otsan taakse ja ojenna takaisin ylös.",
    scope: "global",
  },
  {
    id: "ex_barbell_curl",
    name: "Hauiskääntö tangolla",
    category: "Hauis",
    equipment: "EZ-tanko / suora tanko",
    cue: "Pidä kyynärpäät kyljissä ja rintakehä avoinna. Nosta tanko ylös ilman heilautusta ja laske hallitusti alas.",
    scope: "global",
  },
  {
    id: "ex_db_curl",
    name: "Hauiskääntö käsipainoilla",
    category: "Hauis",
    equipment: "Käsipainot",
    cue: "Pidä kyynärpäät paikallaan ja kierrä kämmenet ylös noston aikana. Laske painot hitaasti takaisin alas täyteen venytykseen.",
    scope: "global",
  },
  {
    id: "ex_hammer_curl",
    name: "Vasarahauiskääntö",
    category: "Hauis",
    equipment: "Käsipainot",
    cue: "Pidä ranteet neutraalina ja kyynärpäät lähellä vartaloa. Nosta painot hallitusti ylös ja laske alas ilman heilautusta.",
    scope: "global",
  },
  {
    id: "ex_preacher_curl",
    name: "Scott-hauiskääntö",
    category: "Hauis",
    equipment: "Scott-penkki",
    cue: "Pidä olkavarret tukevasti padilla ja hartiat rentoina. Tee täysi liikerata hallitusti ja vältä painon pudottamista alas.",
    scope: "global",
  },
  {
    id: "ex_cable_curl",
    name: "Hauiskääntö taljassa",
    category: "Hauis",
    equipment: "Talja",
    cue: "Pidä jännitys hauiksessa koko liikkeen ajan ja kyynärpäät paikoillaan. Purista yläasennossa ja palauta hitaasti.",
    scope: "global",
  },
  {
    id: "ex_plank",
    name: "Lankku",
    category: "Core",
    equipment: "Kehonpaino",
    cue: "Purista pakarat ja keskivartalo tiukaksi koko pidon ajan. Pidä vartalo suorassa linjassa ilman että alaselkä notkahtaa.",
    scope: "global",
  },
  {
    id: "ex_side_plank",
    name: "Sivulankku",
    category: "Core",
    equipment: "Kehonpaino",
    cue: "Pidä kyynärpää suoraan olkapään alla ja lantio korkealla. Säilytä vartalo suorassa linjassa koko pidon ajan.",
    scope: "global",
  },
  {
    id: "ex_dead_bug",
    name: "Dead bug",
    category: "Core",
    equipment: "Kehonpaino",
    cue: "Pidä alaselkä kevyesti lattiaa vasten ja kyljet aktiivisina. Ojenna raajat vuorotellen hallitusti ilman että selkä irtoaa alustasta.",
    scope: "global",
  },
  {
    id: "ex_ab_wheel",
    name: "Ab wheel roll-out",
    category: "Core",
    equipment: "Ab wheel",
    cue: "Jännitä keskivartalo ennen rullausta ja pidä lantio hallinnassa. Vie rulla eteen niin pitkälle kuin pystyt ilman että alaselkä notkahtaa.",
    scope: "global",
  },
  {
    id: "ex_hanging_leg_raise",
    name: "Jalkojen nosto roikkuen",
    category: "Core",
    equipment: "Leuanvetotanko",
    cue: "Aloita vakaasta roikunnasta ja pidä lapatuet aktiivisina. Nosta jalat hallitusti ylös ilman heilautusta ja laske rauhassa alas.",
    scope: "global",
  },
  {
    id: "ex_cable_crunch",
    name: "Vatsarutistus taljassa",
    category: "Core",
    equipment: "Talja",
    cue: "Pidä lantio paikallaan ja pyöristä yläselkää vatsan avulla. Rutista hallitusti alas ja palaa ylös ilman että vedät käsillä liikaa.",
    scope: "global",
  },
  {
    id: "ex_russian_twist",
    name: "Russian twist",
    category: "Core",
    equipment: "Levy / käsipaino",
    cue: "Pidä rintakehä ryhdikkäänä ja keskivartalo aktiivisena. Kierrä rintarangasta puolelta toiselle hallitusti ilman pelkkää käsien heilautusta.",
    scope: "global",
  },
  {
    id: "ex_pallof_press",
    name: "Pallof press",
    category: "Core",
    equipment: "Talja / kuminauha",
    cue: "Asetu vakaaseen asentoon ja jännitä keskivartalo. Punnerra kahva eteen ja vastusta taljan vetoa ilman että lantio kiertyy.",
    scope: "global",
  },
  {
    id: "ex_farmers_walk",
    name: "Farmer's walk",
    category: "Koko kroppa",
    equipment: "Käsipainot / farmer-kahvat",
    cue: "Seiso ryhdikkäästi hartiat alhaalla ja pidä ote vahvana. Kävele lyhyin hallituin askelin ilman että kuorma heiluttaa vartaloa.",
    scope: "global",
  },
  {
    id: "ex_sled_push",
    name: "Kelkan työntö",
    category: "Koko kroppa",
    equipment: "Kelkka",
    cue: "Kallista vartalo kevyesti eteen ja pidä keskivartalo tiukkana. Työnnä kelkkaa tasaisella rytmillä koko jalkapohjan kautta.",
    scope: "global",
  },
  {
    id: "ex_kettlebell_swing",
    name: "Kahvakuulaheilautus",
    category: "Takaketju",
    equipment: "Kahvakuula",
    cue: "Vie lantio taakse ja pidä selkä neutraalina ennen heilautusta. Räjäytä lantio eteen ja anna käsien vain ohjata kuulaa.",
    scope: "global",
  },
  {
    id: "ex_thruster",
    name: "Thruster",
    category: "Koko kroppa",
    equipment: "Levantotanko / käsipainot",
    cue: "Pidä keskivartalo tiukkana ja laskeudu hallittuun etukyykkyyn. Nouse voimakkaasti ylös ja jatka liike suoraan pystypunnerrukseksi.",
    scope: "global",
  },
];

export const demoState: AppState = {
  users: [
    {
      id: "user_admin_1",
      role: "admin",
      fullName: "Aino Admin",
      email: "admin@rooki.fit",
      status: "active",
      demoPassword: "demo123",
      createdAt: iso(-30),
      updatedAt: iso(-2),
    },
    {
      id: "user_coach_1",
      role: "coach",
      fullName: "Mika Valmentaja",
      email: "coach@rooki.fit",
      status: "active",
      demoPassword: "demo123",
      createdAt: iso(-25),
      updatedAt: iso(-1),
    },
    {
      id: "user_athlete_1",
      role: "athlete",
      fullName: "Sara Treenaaja",
      email: "sara@rooki.fit",
      status: "active",
      demoPassword: "demo123",
      heightCm: 168,
      weightKg: 67.8,
      waistCm: 74,
      createdAt: iso(-20),
      updatedAt: iso(-1),
    },
    {
      id: "user_athlete_2",
      role: "athlete",
      fullName: "Elias Kehittyjä",
      email: "elias@rooki.fit",
      status: "active",
      demoPassword: "demo123",
      heightCm: 182,
      weightKg: 84.6,
      waistCm: 88,
      createdAt: iso(-18),
      updatedAt: iso(-1),
    },
    {
      id: "user_athlete_3",
      role: "athlete",
      fullName: "Noora Kutsu",
      email: "noora@rooki.fit",
      status: "invited",
      createdAt: iso(-1),
      updatedAt: iso(-1),
    },
  ],
  bodyMeasurements: [
    { id: "measurement_1", userId: "user_athlete_1", heightCm: 168, weightKg: 69.4, waistCm: 76, measuredAt: iso(-42), createdAt: iso(-42) },
    { id: "measurement_2", userId: "user_athlete_1", heightCm: 168, weightKg: 68.9, waistCm: 75.5, measuredAt: iso(-35), createdAt: iso(-35) },
    { id: "measurement_3", userId: "user_athlete_1", heightCm: 168, weightKg: 68.5, waistCm: 75, measuredAt: iso(-28), createdAt: iso(-28) },
    { id: "measurement_4", userId: "user_athlete_1", heightCm: 168, weightKg: 68.2, waistCm: 74.5, measuredAt: iso(-21), createdAt: iso(-21) },
    { id: "measurement_5", userId: "user_athlete_1", heightCm: 168, weightKg: 68, waistCm: 74, measuredAt: iso(-14), createdAt: iso(-14) },
    { id: "measurement_6", userId: "user_athlete_1", heightCm: 168, weightKg: 67.8, waistCm: 74, measuredAt: iso(-7), createdAt: iso(-7) },
    { id: "measurement_7", userId: "user_athlete_2", heightCm: 182, weightKg: 86.2, waistCm: 90, measuredAt: iso(-35), createdAt: iso(-35) },
    { id: "measurement_8", userId: "user_athlete_2", heightCm: 182, weightKg: 85.7, waistCm: 89, measuredAt: iso(-21), createdAt: iso(-21) },
    { id: "measurement_9", userId: "user_athlete_2", heightCm: 182, weightKg: 84.6, waistCm: 88, measuredAt: iso(-7), createdAt: iso(-7) },
  ],
  assignments: [
    {
      id: "assignment_1",
      coachId: "user_coach_1",
      athleteId: "user_athlete_1",
      active: true,
      createdAt: iso(-20),
    },
    {
      id: "assignment_2",
      coachId: "user_coach_1",
      athleteId: "user_athlete_2",
      active: true,
      createdAt: iso(-18),
    },
  ],
  exercises: defaultGlobalExercises,
  templates: [
    {
      id: "template_lower_1",
      coachId: "user_coach_1",
      title: "Voimapäivä A",
      description: "Alavartalon voimapainotteinen treeni viikon alkuun.",
      goal: "Perusvoima + liikeradan laatu",
      splitType: "lower",
      status: "published",
      blocks: [
        {
          id: "block_1",
          title: "Pääsarjat",
          note: "Nosta painoja vain, jos kaikki sarjat tuntuvat hallituilta.",
          exercises: [
            {
              id: "template_ex_1",
              exerciseId: "ex_back_squat",
              instruction: "Pidä 2s pysäytys alhaalla ensimmäisissä kahdessa sarjassa.",
              sets: [
                { id: "set_1", label: "1", targetReps: 5, targetLoad: 70, restSeconds: 120 },
                { id: "set_2", label: "2", targetReps: 5, targetLoad: 70, restSeconds: 120 },
                { id: "set_3", label: "3", targetReps: 5, targetLoad: 72.5, restSeconds: 150 },
              ],
            },
            {
              id: "template_ex_2",
              exerciseId: "ex_romanian_deadlift",
              instruction: "Laske 3 sekuntia alas.",
              sets: [
                { id: "set_4", label: "1", targetReps: 8, targetLoad: 55, restSeconds: 90 },
                { id: "set_5", label: "2", targetReps: 8, targetLoad: 55, restSeconds: 90 },
                { id: "set_6", label: "3", targetReps: 8, targetLoad: 57.5, restSeconds: 90 },
              ],
            },
            {
              id: "template_ex_7",
              exerciseId: "ex_leg_curl",
              instruction: "Purista takareisiä yläasennossa ja laske hallitusti alas.",
              sets: [
                { id: "set_19", label: "1", targetReps: 12, targetLoad: 30, restSeconds: 60 },
                { id: "set_20", label: "2", targetReps: 12, targetLoad: 30, restSeconds: 60 },
                { id: "set_21", label: "3", targetReps: 12, targetLoad: 32.5, restSeconds: 60 },
              ],
            },
            {
              id: "template_ex_8",
              exerciseId: "ex_calf_raise_standing",
              instruction: "Käy täydessä venytyksessä ja pysäytä hetkeksi yläasennossa.",
              sets: [
                { id: "set_22", label: "1", targetReps: 15, targetLoad: 20, restSeconds: 45 },
                { id: "set_23", label: "2", targetReps: 15, targetLoad: 20, restSeconds: 45 },
                { id: "set_24", label: "3", targetReps: 15, targetLoad: 25, restSeconds: 45 },
              ],
            },
          ],
        },
      ],
      createdAt: iso(-14),
      updatedAt: iso(-3),
      createdBy: "user_coach_1",
      updatedBy: "user_coach_1",
    },
    {
      id: "template_upper_1",
      coachId: "user_coach_1",
      title: "Ylävartalo B",
      description: "Työntö-veto -yhdistelmä progressiolla.",
      goal: "Lihaskestävyys ja kontrolli",
      splitType: "upper",
      status: "published",
      blocks: [
        {
          id: "block_2",
          title: "Työosio",
          exercises: [
            {
              id: "template_ex_3",
              exerciseId: "ex_bench_press",
              instruction: "Pidä 1 toisto varaa jokaisessa sarjassa.",
              sets: [
                { id: "set_7", label: "1", targetReps: 8, targetLoad: 45, restSeconds: 90 },
                { id: "set_8", label: "2", targetReps: 8, targetLoad: 45, restSeconds: 90 },
                { id: "set_9", label: "3", targetReps: 8, targetLoad: 47.5, restSeconds: 90 },
              ],
            },
            {
              id: "template_ex_4",
              exerciseId: "ex_row",
              instruction: "Pysäytä yläasennossa sekunti.",
              sets: [
                { id: "set_10", label: "1", targetReps: 10, targetLoad: 18, restSeconds: 60 },
                { id: "set_11", label: "2", targetReps: 10, targetLoad: 18, restSeconds: 60 },
                { id: "set_12", label: "3", targetReps: 10, targetLoad: 20, restSeconds: 60 },
              ],
            },
            {
              id: "template_ex_9",
              exerciseId: "ex_overhead_press",
              instruction: "Pidä keskivartalo tiukkana ja työnnä suoraan ylös.",
              sets: [
                { id: "set_25", label: "1", targetReps: 8, targetLoad: 25, restSeconds: 75 },
                { id: "set_26", label: "2", targetReps: 8, targetLoad: 25, restSeconds: 75 },
                { id: "set_27", label: "3", targetReps: 8, targetLoad: 27.5, restSeconds: 75 },
              ],
            },
            {
              id: "template_ex_10",
              exerciseId: "ex_lat_pulldown",
              instruction: "Vedä kyynärpäät alas ja taakse ilman nykäisyä.",
              sets: [
                { id: "set_28", label: "1", targetReps: 10, targetLoad: 40, restSeconds: 60 },
                { id: "set_29", label: "2", targetReps: 10, targetLoad: 40, restSeconds: 60 },
                { id: "set_30", label: "3", targetReps: 10, targetLoad: 45, restSeconds: 60 },
              ],
            },
          ],
        },
      ],
      createdAt: iso(-12),
      updatedAt: iso(-2),
      createdBy: "user_coach_1",
      updatedBy: "user_coach_1",
    },
    {
      id: "template_full_1",
      coachId: "user_coach_1",
      title: "Koko kroppa C",
      description: "Koko kehon kontrolli- ja tukivoimapäivä viikon loppuun.",
      goal: "Tasapaino + liikehallinta + kokonaiskuorma",
      splitType: "full_body",
      status: "published",
      blocks: [
        {
          id: "block_3",
          title: "Full body flow",
          exercises: [
            {
              id: "template_ex_5",
              exerciseId: "ex_split_squat",
              instruction: "Pidä lantio suorassa ja kontrolloi jokainen toisto.",
              sets: [
                { id: "set_13", label: "1", targetReps: 10, targetLoad: 14, restSeconds: 75 },
                { id: "set_14", label: "2", targetReps: 10, targetLoad: 14, restSeconds: 75 },
                { id: "set_15", label: "3", targetReps: 10, targetLoad: 16, restSeconds: 75 },
              ],
            },
            {
              id: "template_ex_6",
              exerciseId: "ex_plank",
              instruction: "Pidä keskivartalo aktiivisena koko sarjan ajan.",
              sets: [
                { id: "set_16", label: "1", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
                { id: "set_17", label: "2", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
                { id: "set_18", label: "3", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
              ],
            },
            {
              id: "template_ex_11",
              exerciseId: "ex_incline_db_press",
              instruction: "Pidä lavat tuettuina penkkiin ja työnnä tasaisesti ylös.",
              sets: [
                { id: "set_31", label: "1", targetReps: 10, targetLoad: 16, restSeconds: 75 },
                { id: "set_32", label: "2", targetReps: 10, targetLoad: 16, restSeconds: 75 },
                { id: "set_33", label: "3", targetReps: 10, targetLoad: 18, restSeconds: 75 },
              ],
            },
            {
              id: "template_ex_12",
              exerciseId: "ex_seated_cable_row",
              instruction: "Vedä kyynärpäät taakse ja pysäytä hetkeksi loppuasentoon.",
              sets: [
                { id: "set_34", label: "1", targetReps: 12, targetLoad: 35, restSeconds: 60 },
                { id: "set_35", label: "2", targetReps: 12, targetLoad: 35, restSeconds: 60 },
                { id: "set_36", label: "3", targetReps: 12, targetLoad: 40, restSeconds: 60 },
              ],
            },
          ],
        },
      ],
      createdAt: iso(-10),
      updatedAt: iso(-2),
      createdBy: "user_coach_1",
      updatedBy: "user_coach_1",
    },
  ],
  plans: [
    {
      id: "plan_1",
      coachId: "user_coach_1",
      athleteId: "user_athlete_1",
      title: "Sara 4 viikon voimaohjelma",
      workouts: [
        {
          id: "program_workout_upper_1",
          name: "Ylävartalo B",
          splitType: "upper",
          defaultRestSeconds: 90,
          exercises: [
            {
              id: "program_ex_1",
              exerciseId: "ex_bench_press",
              exerciseName: "Penkkipunnerrus",
              muscleGroup: "chest",
              instruction: "Pidä 1 toisto varaa jokaisessa sarjassa.",
              sets: [
                { id: "program_set_1", label: "1", targetReps: 8, targetLoad: 45, restSeconds: 90 },
                { id: "program_set_2", label: "2", targetReps: 8, targetLoad: 45, restSeconds: 90 },
                { id: "program_set_3", label: "3", targetReps: 8, targetLoad: 47.5, restSeconds: 90 },
              ],
            },
            {
              id: "program_ex_2",
              exerciseId: "ex_row",
              exerciseName: "Kulmasoutu",
              muscleGroup: "back",
              instruction: "Pysäytä yläasennossa sekunti.",
              sets: [
                { id: "program_set_4", label: "1", targetReps: 10, targetLoad: 18, restSeconds: 60 },
                { id: "program_set_5", label: "2", targetReps: 10, targetLoad: 18, restSeconds: 60 },
                { id: "program_set_6", label: "3", targetReps: 10, targetLoad: 20, restSeconds: 60 },
              ],
            },
            {
              id: "program_ex_7",
              exerciseId: "ex_overhead_press",
              exerciseName: "Pystypunnerrus tangolla",
              muscleGroup: "shoulders",
              instruction: "Pidä keskivartalo tiukkana ja työnnä suoraan ylös.",
              sets: [
                { id: "program_set_19", label: "1", targetReps: 8, targetLoad: 25, restSeconds: 75 },
                { id: "program_set_20", label: "2", targetReps: 8, targetLoad: 25, restSeconds: 75 },
                { id: "program_set_21", label: "3", targetReps: 8, targetLoad: 27.5, restSeconds: 75 },
              ],
            },
            {
              id: "program_ex_8",
              exerciseId: "ex_lat_pulldown",
              exerciseName: "Ylätalja",
              muscleGroup: "back",
              instruction: "Vedä kyynärpäät alas ja taakse ilman nykäisyä.",
              sets: [
                { id: "program_set_22", label: "1", targetReps: 10, targetLoad: 40, restSeconds: 60 },
                { id: "program_set_23", label: "2", targetReps: 10, targetLoad: 40, restSeconds: 60 },
                { id: "program_set_24", label: "3", targetReps: 10, targetLoad: 45, restSeconds: 60 },
              ],
            },
          ],
        },
        {
          id: "program_workout_lower_1",
          name: "Voimapäivä A",
          splitType: "lower",
          defaultRestSeconds: 120,
          exercises: [
            {
              id: "program_ex_3",
              exerciseId: "ex_back_squat",
              exerciseName: "Takakyykky",
              muscleGroup: "legs",
              instruction: "Pidä 2s pysäytys alhaalla ensimmäisissä kahdessa sarjassa.",
              sets: [
                { id: "program_set_7", label: "1", targetReps: 5, targetLoad: 70, restSeconds: 120 },
                { id: "program_set_8", label: "2", targetReps: 5, targetLoad: 70, restSeconds: 120 },
                { id: "program_set_9", label: "3", targetReps: 5, targetLoad: 72.5, restSeconds: 150 },
              ],
            },
            {
              id: "program_ex_4",
              exerciseId: "ex_romanian_deadlift",
              exerciseName: "Romanialainen maastaveto",
              muscleGroup: "legs",
              instruction: "Laske 3 sekuntia alas.",
              sets: [
                { id: "program_set_10", label: "1", targetReps: 8, targetLoad: 55, restSeconds: 90 },
                { id: "program_set_11", label: "2", targetReps: 8, targetLoad: 55, restSeconds: 90 },
                { id: "program_set_12", label: "3", targetReps: 8, targetLoad: 57.5, restSeconds: 90 },
              ],
            },
            {
              id: "program_ex_9",
              exerciseId: "ex_leg_curl",
              exerciseName: "Takareisikoukistus",
              muscleGroup: "legs",
              instruction: "Purista takareisiä yläasennossa ja laske hallitusti alas.",
              sets: [
                { id: "program_set_25", label: "1", targetReps: 12, targetLoad: 30, restSeconds: 60 },
                { id: "program_set_26", label: "2", targetReps: 12, targetLoad: 30, restSeconds: 60 },
                { id: "program_set_27", label: "3", targetReps: 12, targetLoad: 32.5, restSeconds: 60 },
              ],
            },
            {
              id: "program_ex_10",
              exerciseId: "ex_calf_raise_standing",
              exerciseName: "Pohjenousu seisten",
              muscleGroup: "legs",
              instruction: "Käy täydessä venytyksessä ja pysäytä hetkeksi yläasennossa.",
              sets: [
                { id: "program_set_28", label: "1", targetReps: 15, targetLoad: 20, restSeconds: 45 },
                { id: "program_set_29", label: "2", targetReps: 15, targetLoad: 20, restSeconds: 45 },
                { id: "program_set_30", label: "3", targetReps: 15, targetLoad: 25, restSeconds: 45 },
              ],
            },
          ],
        },
        {
          id: "program_workout_full_1",
          name: "Koko kroppa C",
          splitType: "full_body",
          defaultRestSeconds: 75,
          exercises: [
            {
              id: "program_ex_5",
              exerciseId: "ex_split_squat",
              exerciseName: "Bulgarialainen askelkyykky",
              muscleGroup: "legs",
              instruction: "Pidä lantio suorassa ja kontrolloi jokainen toisto.",
              sets: [
                { id: "program_set_13", label: "1", targetReps: 10, targetLoad: 14, restSeconds: 75 },
                { id: "program_set_14", label: "2", targetReps: 10, targetLoad: 14, restSeconds: 75 },
                { id: "program_set_15", label: "3", targetReps: 10, targetLoad: 16, restSeconds: 75 },
              ],
            },
            {
              id: "program_ex_6",
              exerciseId: "ex_plank",
              exerciseName: "Lankku",
              muscleGroup: "abs",
              instruction: "Pidä keskivartalo aktiivisena koko sarjan ajan.",
              sets: [
                { id: "program_set_16", label: "1", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
                { id: "program_set_17", label: "2", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
                { id: "program_set_18", label: "3", targetReps: 1, restSeconds: 60, notes: "45-60 sekuntia" },
              ],
            },
            {
              id: "program_ex_11",
              exerciseId: "ex_incline_db_press",
              exerciseName: "Vinopenkki käsipainoilla",
              muscleGroup: "chest",
              instruction: "Pidä lavat tuettuina penkkiin ja työnnä tasaisesti ylös.",
              sets: [
                { id: "program_set_31", label: "1", targetReps: 10, targetLoad: 16, restSeconds: 75 },
                { id: "program_set_32", label: "2", targetReps: 10, targetLoad: 16, restSeconds: 75 },
                { id: "program_set_33", label: "3", targetReps: 10, targetLoad: 18, restSeconds: 75 },
              ],
            },
            {
              id: "program_ex_12",
              exerciseId: "ex_seated_cable_row",
              exerciseName: "Istuva soutu taljassa",
              muscleGroup: "back",
              instruction: "Vedä kyynärpäät taakse ja pysäytä hetkeksi loppuasentoon.",
              sets: [
                { id: "program_set_34", label: "1", targetReps: 12, targetLoad: 35, restSeconds: 60 },
                { id: "program_set_35", label: "2", targetReps: 12, targetLoad: 35, restSeconds: 60 },
                { id: "program_set_36", label: "3", targetReps: 12, targetLoad: 40, restSeconds: 60 },
              ],
            },
          ],
        },
      ],
      startDate: iso(-7),
      weekCount: 4,
      createdAt: iso(-7),
      updatedAt: iso(-2),
    },
  ],
  scheduledWorkouts: [
    {
      id: "scheduled_5",
      trainingPlanId: "plan_1",
      templateId: "template_upper_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      title: "Ylävartalo B",
      scheduledDate: iso(-8),
      status: "completed",
      createdAt: iso(-10),
      updatedAt: iso(-8),
      completedAt: iso(-8),
    },
    {
      id: "scheduled_1",
      trainingPlanId: "plan_1",
      templateId: "template_lower_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      title: "Voimapäivä A",
      scheduledDate: iso(-1),
      status: "completed",
      createdAt: iso(-4),
      updatedAt: iso(-1),
      completedAt: iso(-1),
    },
    {
      id: "scheduled_2",
      trainingPlanId: "plan_1",
      templateId: "template_upper_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      title: "Ylävartalo B",
      scheduledDate: iso(0),
      status: "in_progress",
      createdAt: iso(-3),
      updatedAt: iso(0),
    },
    {
      id: "scheduled_3",
      templateId: "template_lower_1",
      athleteId: "user_athlete_2",
      coachId: "user_coach_1",
      title: "Voimapäivä A",
      scheduledDate: iso(1),
      status: "cancelled",
      createdAt: iso(-2),
      updatedAt: iso(-2),
    },
    {
      id: "scheduled_4",
      trainingPlanId: "plan_1",
      templateId: "template_full_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      title: "Koko kroppa C",
      scheduledDate: iso(2),
      status: "cancelled",
      createdAt: iso(-2),
      updatedAt: iso(-2),
    },
  ],
  sessions: [
    {
      id: "session_3",
      scheduledWorkoutId: "scheduled_5",
      athleteId: "user_athlete_1",
      startedAt: iso(-8),
      completedAt: iso(-8),
      updatedAt: iso(-8),
      energyLevel: 4,
      setLogs: [
        {
          id: "log_9",
          scheduledWorkoutId: "scheduled_5",
          templateExerciseId: "template_ex_3",
          setId: "set_7",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "1",
          targetReps: 8,
          targetLoad: 45,
          actualReps: 8,
          actualLoad: 45,
          done: true,
        },
        {
          id: "log_10",
          scheduledWorkoutId: "scheduled_5",
          templateExerciseId: "template_ex_3",
          setId: "set_8",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "2",
          targetReps: 8,
          targetLoad: 45,
          actualReps: 8,
          actualLoad: 45,
          done: true,
        },
        {
          id: "log_11",
          scheduledWorkoutId: "scheduled_5",
          templateExerciseId: "template_ex_4",
          setId: "set_10",
          exerciseId: "ex_row",
          exerciseName: "Kulmasoutu",
          setLabel: "1",
          targetReps: 10,
          targetLoad: 18,
          actualReps: 10,
          actualLoad: 18,
          done: true,
        },
      ],
    },
    {
      id: "session_1",
      scheduledWorkoutId: "scheduled_1",
      athleteId: "user_athlete_1",
      startedAt: iso(-1),
      completedAt: iso(-1),
      updatedAt: iso(-1),
      energyLevel: 4,
      setLogs: [
        {
          id: "log_1",
          scheduledWorkoutId: "scheduled_1",
          templateExerciseId: "template_ex_1",
          setId: "set_1",
          exerciseId: "ex_back_squat",
          exerciseName: "Takakyykky",
          setLabel: "1",
          targetReps: 5,
          targetLoad: 70,
          actualReps: 5,
          actualLoad: 70,
          done: true,
        },
        {
          id: "log_2",
          scheduledWorkoutId: "scheduled_1",
          templateExerciseId: "template_ex_1",
          setId: "set_2",
          exerciseId: "ex_back_squat",
          exerciseName: "Takakyykky",
          setLabel: "2",
          targetReps: 5,
          targetLoad: 70,
          actualReps: 5,
          actualLoad: 70,
          done: true,
        },
      ],
    },
    {
      id: "session_2",
      scheduledWorkoutId: "scheduled_2",
      athleteId: "user_athlete_1",
      startedAt: iso(0),
      updatedAt: iso(0),
      energyLevel: 3,
      setLogs: [
        {
          id: "log_3",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "template_ex_3",
          setId: "set_7",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "1",
          targetReps: 8,
          targetLoad: 45,
          actualReps: 8,
          actualLoad: 45,
          done: true,
        },
        {
          id: "log_4",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "template_ex_3",
          setId: "set_8",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "2",
          targetReps: 8,
          targetLoad: 45,
          done: false,
        },
        {
          id: "log_5",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "template_ex_3",
          setId: "set_9",
          exerciseId: "ex_bench_press",
          exerciseName: "Penkkipunnerrus",
          setLabel: "3",
          targetReps: 8,
          targetLoad: 47.5,
          done: false,
        },
        {
          id: "log_6",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "template_ex_4",
          setId: "set_10",
          exerciseId: "ex_row",
          exerciseName: "Kulmasoutu",
          setLabel: "1",
          targetReps: 10,
          targetLoad: 18,
          done: false,
        },
        {
          id: "log_7",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "template_ex_4",
          setId: "set_11",
          exerciseId: "ex_row",
          exerciseName: "Kulmasoutu",
          setLabel: "2",
          targetReps: 10,
          targetLoad: 18,
          done: false,
        },
        {
          id: "log_8",
          scheduledWorkoutId: "scheduled_2",
          templateExerciseId: "template_ex_4",
          setId: "set_12",
          exerciseId: "ex_row",
          exerciseName: "Kulmasoutu",
          setLabel: "3",
          targetReps: 10,
          targetLoad: 20,
          done: false,
        },
      ],
    },
  ],
  notes: [
    {
      id: "note_1",
      sessionId: "session_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      body: "Takakyykky tuntui vakaalta. Voidaan nostaa 2,5 kg ensi viikolla.",
      createdAt: iso(-1),
      updatedAt: iso(-1),
    },
  ],
  conversationEntries: [
    {
      id: "conversation_1",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      authorUserId: "user_athlete_1",
      authorRole: "athlete",
      type: "comment",
      body: "Kyykyn viimeinen sarja oli jo aika raskas, mutta tekniikka pysyi kasassa.",
      contextType: "workout",
      contextId: "scheduled_1",
      contextLabel: "Alakroppa 1",
      createdAt: iso(-1),
      readByUserIds: ["user_athlete_1"],
    },
    {
      id: "conversation_2",
      athleteId: "user_athlete_1",
      coachId: "user_coach_1",
      authorUserId: "user_coach_1",
      authorRole: "coach",
      type: "comment",
      body: "Hyvä huomio. Pidetään ensi viikolla sama kuorma ja haetaan puhtaampi loppu.",
      contextType: "workout",
      contextId: "scheduled_1",
      contextLabel: "Alakroppa 1",
      createdAt: iso(0),
      readByUserIds: ["user_coach_1"],
    },
  ],
  invites: [
    {
      id: "invite_1",
      token: "join-noora-demo",
      email: "noora@rooki.fit",
      role: "athlete",
      invitedBy: "user_coach_1",
      coachId: "user_coach_1",
      status: "pending",
      createdAt: iso(-1),
      expiresAt: iso(6),
    },
  ],
  passwordResetRequests: [],
};
